export const world = [
    {
        countryEn: 'Afghanistan',
        countryRu: 'Афганистан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 29121286,
        capitalEn: 'Kabul',
        capitalRu: 'Кабул',
        regionCode: 142,
        countryCode: 4,
        countryCodeLetters: 'AF',
    },
    {
        countryEn: 'Aland Islands',
        countryRu: 'Аландские острова',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 26711,
        capitalEn: 'Mariehamn',
        capitalRu: 'Мариехамн',
        regionCode: 150,
        countryCode: 248,
        countryCodeLetters: 'AX',
    },
    {
        countryEn: 'Albania',
        countryRu: 'Албания',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2986952,
        capitalEn: 'Tirana',
        capitalRu: 'Тирана',
        regionCode: 150,
        countryCode: 8,
        countryCodeLetters: 'AL',
    },
    {
        countryEn: 'Algeria',
        countryRu: 'Алжир',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 34586184,
        capitalEn: 'Algiers',
        capitalRu: 'Алжир',
        regionCode: 2,
        countryCode: 12,
        countryCodeLetters: 'DZ',
    },
    {
        countryEn: 'American Samoa',
        countryRu: 'Американское Самоа',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 57881,
        capitalEn: 'Pago Pago',
        capitalRu: 'Паго-Паго',
        regionCode: 9,
        countryCode: 16,
        countryCodeLetters: 'AS',
    },
    {
        countryEn: 'Andorra',
        countryRu: 'Андорра',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 84000,
        capitalEn: 'Andorra la Vella',
        capitalRu: 'Андорра-ла-Велья',
        regionCode: 150,
        countryCode: 20,
        countryCodeLetters: 'AD',
    },
    {
        countryEn: 'Angola',
        countryRu: 'Ангола',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 13068161,
        capitalEn: 'Luanda',
        capitalRu: 'Луанда',
        regionCode: 2,
        countryCode: 24,
        countryCodeLetters: 'AO',
    },
    {
        countryEn: 'Anguilla',
        countryRu: 'Ангилья',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 13254,
        capitalEn: 'The Valley',
        capitalRu: 'Долина',
        regionCode: 19,
        countryCode: 660,
        countryCodeLetters: 'AI',
    },
    {
        countryEn: 'Antigua & Barbuda',
        countryRu: 'Антигуа и Барбуда',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 86754,
        capitalEn: "St John's",
        capitalRu: 'Сент-Джонс',
        regionCode: 19,
        countryCode: 28,
        countryCodeLetters: 'AG',
    },
    {
        countryEn: 'Argentina',
        countryRu: 'Аргентина',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 41343201,
        capitalEn: 'Buenos Aires',
        capitalRu: 'Буэнос айрес',
        regionCode: 19,
        countryCode: 32,
        countryCodeLetters: 'AR',
    },
    {
        countryEn: 'Armenia',
        countryRu: 'Армения',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 2968000,
        capitalEn: 'Yerevan',
        capitalRu: 'Ереван',
        regionCode: 142,
        countryCode: 51,
        countryCodeLetters: 'AM',
    },
    {
        countryEn: 'Aruba',
        countryRu: 'Аруба',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 71566,
        capitalEn: 'Oranjestad',
        capitalRu: 'Ораньестад',
        regionCode: 19,
        countryCode: 533,
        countryCodeLetters: 'AW',
    },
    {
        countryEn: 'Australia',
        countryRu: 'Австралия',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 21515754,
        capitalEn: 'Canberra',
        capitalRu: 'Канберра',
        regionCode: 9,
        countryCode: 36,
        countryCodeLetters: 'AU',
    },
    {
        countryEn: 'Austria',
        countryRu: 'Австрия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 8205000,
        capitalEn: 'Vienna',
        capitalRu: 'Вена',
        regionCode: 150,
        countryCode: 40,
        countryCodeLetters: 'AT',
    },
    {
        countryEn: 'Azerbaijan',
        countryRu: 'Азербайджан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 8303512,
        capitalEn: 'Baku',
        capitalRu: 'Баку',
        regionCode: 142,
        countryCode: 31,
        countryCodeLetters: 'AZ',
    },
    {
        countryEn: 'Bahamas',
        countryRu: 'Багамы',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 301790,
        capitalEn: 'Nassau',
        capitalRu: 'Нассау',
        regionCode: 19,
        countryCode: 44,
        countryCodeLetters: 'BS',
    },
    {
        countryEn: 'Bahrain',
        countryRu: 'Бахрейн',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 738004,
        capitalEn: 'Manama',
        capitalRu: 'Манама',
        regionCode: 142,
        countryCode: 48,
        countryCodeLetters: 'BH',
    },
    {
        countryEn: 'Bangladesh',
        countryRu: 'Бангладеш',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 156118464,
        capitalEn: 'Dhaka',
        capitalRu: 'Дакка',
        regionCode: 142,
        countryCode: 50,
        countryCodeLetters: 'BD',
    },
    {
        countryEn: 'Barbados',
        countryRu: 'Барбадос',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 285653,
        capitalEn: 'Bridgetown',
        capitalRu: 'Бриджтаун',
        regionCode: 19,
        countryCode: 52,
        countryCodeLetters: 'BB',
    },
    {
        countryEn: 'Belarus',
        countryRu: 'Беларусь',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 9685000,
        capitalEn: 'Minsk',
        capitalRu: 'Минск',
        regionCode: 150,
        countryCode: 112,
        countryCodeLetters: 'BY',
    },
    {
        countryEn: 'Belgium',
        countryRu: 'Бельгия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 10403000,
        capitalEn: 'Brussels',
        capitalRu: 'Брюссель',
        regionCode: 150,
        countryCode: 56,
        countryCodeLetters: 'BE',
    },
    {
        countryEn: 'Belize',
        countryRu: 'Белиз',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 314522,
        capitalEn: 'Belmopan',
        capitalRu: 'Бельмопан',
        regionCode: 19,
        countryCode: 84,
        countryCodeLetters: 'BZ',
    },
    {
        countryEn: 'Benin',
        countryRu: 'Бенин',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 9056010,
        capitalEn: 'Porto-Novo',
        capitalRu: 'Порто-Ново',
        regionCode: 2,
        countryCode: 204,
        countryCodeLetters: 'BJ',
    },
    {
        countryEn: 'Bermuda',
        countryRu: 'Бермуды',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 65365,
        capitalEn: 'Hamilton',
        capitalRu: 'Гамильтон',
        regionCode: 19,
        countryCode: 60,
        countryCodeLetters: 'BM',
    },
    {
        countryEn: 'Bhutan',
        countryRu: 'Бутан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 699847,
        capitalEn: 'Thimphu',
        capitalRu: 'Тхимпху',
        regionCode: 142,
        countryCode: 64,
        countryCodeLetters: 'BT',
    },
    {
        countryEn: 'Bolivia',
        countryRu: 'Боливия',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 9947418,
        capitalEn: 'Sucre',
        capitalRu: 'Сукре',
        regionCode: 19,
        countryCode: 68,
        countryCodeLetters: 'BO',
    },
    {
        countryEn: 'Caribbean Netherlands',
        countryRu: 'Карибские Нидерланды',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 18012,
        capitalEn: 'Kralendijk',
        capitalRu: 'Кралендейк',
        regionCode: 19,
        countryCode: 535,
        countryCodeLetters: 'BQ',
    },
    {
        countryEn: 'Bosnia & Herzegovina',
        countryRu: 'Босния и Герцеговина',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 4590000,
        capitalEn: 'Sarajevo',
        capitalRu: 'Сараево',
        regionCode: 150,
        countryCode: 70,
        countryCodeLetters: 'BA',
    },
    {
        countryEn: 'Botswana',
        countryRu: 'Ботсвана',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 2029307,
        capitalEn: 'Gaborone',
        capitalRu: 'Габороне',
        regionCode: 2,
        countryCode: 72,
        countryCodeLetters: 'BW',
    },
    {
        countryEn: 'Bouvet Island',
        countryRu: 'Остров Буве',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 0,
        capitalEn: '',
        capitalRu: '',
        regionCode: 19,
        countryCode: 74,
        countryCodeLetters: 'BV',
    },
    {
        countryEn: 'Brazil',
        countryRu: 'Бразилия',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 201103330,
        capitalEn: 'Brasília',
        capitalRu: 'Бразилиа',
        regionCode: 19,
        countryCode: 76,
        countryCodeLetters: 'BR',
    },
    {
        countryEn: 'British Indian Ocean Territory',
        countryRu: 'Британская территория Индийского океана',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 4000,
        capitalEn: '',
        capitalRu: '',
        regionCode: 2,
        countryCode: 86,
        countryCodeLetters: 'IO',
    },
    {
        countryEn: 'Brunei',
        countryRu: 'Бруней',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 395027,
        capitalEn: 'Bandar Seri Begawan',
        capitalRu: 'Бандар-Сери-Бегаван',
        regionCode: 142,
        countryCode: 96,
        countryCodeLetters: 'BN',
    },
    {
        countryEn: 'Bulgaria',
        countryRu: 'Болгария',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 7000039,
        capitalEn: 'Sofia',
        capitalRu: 'София',
        regionCode: 150,
        countryCode: 100,
        countryCodeLetters: 'BG',
    },
    {
        countryEn: 'Burkina Faso',
        countryRu: 'Буркина-Фасо',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 16241811,
        capitalEn: 'Ouagadougou',
        capitalRu: 'Уагадугу',
        regionCode: 2,
        countryCode: 854,
        countryCodeLetters: 'BF',
    },
    {
        countryEn: 'Burundi',
        countryRu: 'Бурунди',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 9863117,
        capitalEn: 'Gitega',
        capitalRu: 'Гитега',
        regionCode: 2,
        countryCode: 108,
        countryCodeLetters: 'BI',
    },
    {
        countryEn: 'Cape Verde',
        countryRu: 'Кабо-Верде',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 508659,
        capitalEn: 'Praia',
        capitalRu: 'Прая',
        regionCode: 2,
        countryCode: 132,
        countryCodeLetters: 'CV',
    },
    {
        countryEn: 'Cambodia',
        countryRu: 'Камбоджа',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 14453680,
        capitalEn: 'Phnom Penh',
        capitalRu: 'Пномпень',
        regionCode: 142,
        countryCode: 116,
        countryCodeLetters: 'KH',
    },
    {
        countryEn: 'Cameroon',
        countryRu: 'Камерун',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 19294149,
        capitalEn: 'Yaoundé',
        capitalRu: 'Яунде',
        regionCode: 2,
        countryCode: 120,
        countryCodeLetters: 'CM',
    },
    {
        countryEn: 'Canada',
        countryRu: 'Канада',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 33679000,
        capitalEn: 'Ottawa',
        capitalRu: 'Оттава',
        regionCode: 19,
        countryCode: 124,
        countryCodeLetters: 'CA',
    },
    {
        countryEn: 'Cayman Islands',
        countryRu: 'Каймановы острова',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 44270,
        capitalEn: 'George Town',
        capitalRu: 'Джорджтаун',
        regionCode: 19,
        countryCode: 136,
        countryCodeLetters: 'KY',
    },
    {
        countryEn: 'Central African Republic',
        countryRu: 'Центрально-Африканская Республика',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 4844927,
        capitalEn: 'Bangui',
        capitalRu: 'Банги',
        regionCode: 2,
        countryCode: 140,
        countryCodeLetters: 'CF',
    },
    {
        countryEn: 'Chad',
        countryRu: 'Чад',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 10543464,
        capitalEn: "N'Djamena",
        capitalRu: 'Нджамена',
        regionCode: 2,
        countryCode: 148,
        countryCodeLetters: 'TD',
    },
    {
        countryEn: 'Chile',
        countryRu: 'Чили',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 16746491,
        capitalEn: 'Santiago',
        capitalRu: 'Сантьяго',
        regionCode: 19,
        countryCode: 152,
        countryCodeLetters: 'CL',
    },
    {
        countryEn: 'China',
        countryRu: 'Китай',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 1330044000,
        capitalEn: 'Beijing',
        capitalRu: 'Пекин',
        regionCode: 142,
        countryCode: 156,
        countryCodeLetters: 'CN',
    },
    {
        countryEn: 'Christmas Island',
        countryRu: 'Остров Рождества',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 1500,
        capitalEn: 'Flying Fish Cove',
        capitalRu: 'Бухта Летучей Рыбы',
        regionCode: 9,
        countryCode: 162,
        countryCodeLetters: 'CX',
    },
    {
        countryEn: 'Cocos (Keeling) Islands',
        countryRu: 'Кокосовые (Килинг) острова',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 628,
        capitalEn: 'West Island',
        capitalRu: 'Западный остров',
        regionCode: 9,
        countryCode: 166,
        countryCodeLetters: 'CC',
    },
    {
        countryEn: 'Colombia',
        countryRu: 'Колумбия',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 47790000,
        capitalEn: 'Bogotá',
        capitalRu: 'Богота',
        regionCode: 19,
        countryCode: 170,
        countryCodeLetters: 'CO',
    },
    {
        countryEn: 'Comoros',
        countryRu: 'Коморы',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 773407,
        capitalEn: 'Moroni',
        capitalRu: 'Мороний',
        regionCode: 2,
        countryCode: 174,
        countryCodeLetters: 'KM',
    },
    {
        countryEn: 'Congo - Brazzaville',
        countryRu: 'Конго - Браззавиль',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 3039126,
        capitalEn: 'Brazzaville',
        capitalRu: 'Браззавиль',
        regionCode: 2,
        countryCode: 178,
        countryCodeLetters: 'CG',
    },
    {
        countryEn: 'Congo - Kinshasa',
        countryRu: 'Конго - Киншаса',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 70916439,
        capitalEn: 'Kinshasa',
        capitalRu: 'Киншаса',
        regionCode: 2,
        countryCode: 180,
        countryCodeLetters: 'CD',
    },
    {
        countryEn: 'Cook Islands',
        countryRu: 'Острова Кука',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 21388,
        capitalEn: 'Avarua',
        capitalRu: 'Аваруа',
        regionCode: 9,
        countryCode: 184,
        countryCodeLetters: 'CK',
    },
    {
        countryEn: 'Costa Rica',
        countryRu: 'Коста-Рика',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 4516220,
        capitalEn: 'San José',
        capitalRu: 'Сан - Хосе',
        regionCode: 19,
        countryCode: 188,
        countryCodeLetters: 'CR',
    },
    {
        countryEn: 'Côte d’Ivoire',
        countryRu: 'Берег Слоновой Кости',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 21058798,
        capitalEn: 'Yamoussoukro',
        capitalRu: 'Ямусукро',
        regionCode: 2,
        countryCode: 384,
        countryCodeLetters: 'CI',
    },
    {
        countryEn: 'Croatia',
        countryRu: 'Хорватия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 4284889,
        capitalEn: 'Zagreb',
        capitalRu: 'Загреб',
        regionCode: 150,
        countryCode: 191,
        countryCodeLetters: 'HR',
    },
    {
        countryEn: 'Cuba',
        countryRu: 'Куба',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 11423000,
        capitalEn: 'Havana',
        capitalRu: 'Гавана',
        regionCode: 19,
        countryCode: 192,
        countryCodeLetters: 'CU',
    },
    {
        countryEn: 'Curaçao',
        countryRu: 'Кюрасао',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 141766,
        capitalEn: 'Willemstad',
        capitalRu: 'Виллемстад',
        regionCode: 19,
        countryCode: 531,
        countryCodeLetters: 'CW',
    },
    {
        countryEn: 'Cyprus',
        countryRu: 'Кипр',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 1102677,
        capitalEn: 'Nicosia',
        capitalRu: 'Никосия',
        regionCode: 142,
        countryCode: 196,
        countryCodeLetters: 'CY',
    },
    {
        countryEn: 'Czechia',
        countryRu: 'Чехия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 10476000,
        capitalEn: 'Prague',
        capitalRu: 'Прага',
        regionCode: 150,
        countryCode: 203,
        countryCodeLetters: 'CZ',
    },
    {
        countryEn: 'Denmark',
        countryRu: 'Дания',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 5484000,
        capitalEn: 'Copenhagen',
        capitalRu: 'Копенгаген',
        regionCode: 150,
        countryCode: 208,
        countryCodeLetters: 'DK',
    },
    {
        countryEn: 'Djibouti',
        countryRu: 'Джибути',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 740528,
        capitalEn: 'Djibouti',
        capitalRu: 'Джибути',
        regionCode: 2,
        countryCode: 262,
        countryCodeLetters: 'DJ',
    },
    {
        countryEn: 'Dominica',
        countryRu: 'Доминика',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 72813,
        capitalEn: 'Roseau',
        capitalRu: 'Розо',
        regionCode: 19,
        countryCode: 212,
        countryCodeLetters: 'DM',
    },
    {
        countryEn: 'Dominican Republic',
        countryRu: 'Доминиканская Республика',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 9823821,
        capitalEn: 'Santo Domingo',
        capitalRu: 'Санто-Доминго',
        regionCode: 19,
        countryCode: 214,
        countryCodeLetters: 'DO',
    },
    {
        countryEn: 'Ecuador',
        countryRu: 'Эквадор',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 14790608,
        capitalEn: 'Quito',
        capitalRu: 'Кито',
        regionCode: 19,
        countryCode: 218,
        countryCodeLetters: 'EC',
    },
    {
        countryEn: 'Egypt',
        countryRu: 'Египет',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 80471869,
        capitalEn: 'Cairo',
        capitalRu: 'Каир',
        regionCode: 2,
        countryCode: 818,
        countryCodeLetters: 'EG',
    },
    {
        countryEn: 'El Salvador',
        countryRu: 'Сальвадор',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 6052064,
        capitalEn: 'San Salvador',
        capitalRu: 'Сан-Сальвадор',
        regionCode: 19,
        countryCode: 222,
        countryCodeLetters: 'SV',
    },
    {
        countryEn: 'Equatorial Guinea',
        countryRu: 'Экваториальная Гвинея',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1014999,
        capitalEn: 'Malabo',
        capitalRu: 'Малабо',
        regionCode: 2,
        countryCode: 226,
        countryCodeLetters: 'GQ',
    },
    {
        countryEn: 'Eritrea',
        countryRu: 'Эритрея',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 5792984,
        capitalEn: 'Asmara',
        capitalRu: 'Асмэра',
        regionCode: 2,
        countryCode: 232,
        countryCodeLetters: 'ER',
    },
    {
        countryEn: 'Estonia',
        countryRu: 'Эстония',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 1291170,
        capitalEn: 'Tallinn',
        capitalRu: 'Таллинн',
        regionCode: 150,
        countryCode: 233,
        countryCodeLetters: 'EE',
    },
    {
        countryEn: 'Eswatini',
        countryRu: 'Эсватини',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1354051,
        capitalEn: 'Mbabane',
        capitalRu: 'Мбабане',
        regionCode: 2,
        countryCode: 748,
        countryCodeLetters: 'SZ',
    },
    {
        countryEn: 'Ethiopia',
        countryRu: 'Эфиопия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 88013491,
        capitalEn: 'Addis Ababa',
        capitalRu: 'Аддис-Абеба',
        regionCode: 2,
        countryCode: 231,
        countryCodeLetters: 'ET',
    },
    {
        countryEn: 'Falkland Islands',
        countryRu: 'Фолклендские острова',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 2638,
        capitalEn: 'Stanley',
        capitalRu: 'Стэнли',
        regionCode: 19,
        countryCode: 238,
        countryCodeLetters: 'FK',
    },
    {
        countryEn: 'Faroe Islands',
        countryRu: 'Фарерские острова',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 48228,
        capitalEn: 'Tórshavn',
        capitalRu: 'Торсхавн',
        regionCode: 150,
        countryCode: 234,
        countryCodeLetters: 'FO',
    },
    {
        countryEn: 'Fiji',
        countryRu: 'Фиджи',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 875983,
        capitalEn: 'Suva',
        capitalRu: 'Сува',
        regionCode: 9,
        countryCode: 242,
        countryCodeLetters: 'FJ',
    },
    {
        countryEn: 'Finland',
        countryRu: 'Финляндия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 5244000,
        capitalEn: 'Helsinki',
        capitalRu: 'Хельсинки',
        regionCode: 150,
        countryCode: 246,
        countryCodeLetters: 'FI',
    },
    {
        countryEn: 'France',
        countryRu: 'Франция',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 64768389,
        capitalEn: 'Paris',
        capitalRu: 'Париж',
        regionCode: 150,
        countryCode: 250,
        countryCodeLetters: 'FR',
    },
    {
        countryEn: 'French Guiana',
        countryRu: 'Французская Гвиана',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 195506,
        capitalEn: 'Cayenne',
        capitalRu: 'Кайенна',
        regionCode: 19,
        countryCode: 254,
        countryCodeLetters: 'GF',
    },
    {
        countryEn: 'French Polynesia',
        countryRu: 'Французская Полинезия',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 270485,
        capitalEn: 'Papeete',
        capitalRu: 'Папеэте',
        regionCode: 9,
        countryCode: 258,
        countryCodeLetters: 'PF',
    },
    {
        countryEn: 'French Southern Territories',
        countryRu: 'Южные Французские Территории',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 140,
        capitalEn: 'Port-aux-Français',
        capitalRu: 'Порт-о-Франсэ',
        regionCode: 2,
        countryCode: 260,
        countryCodeLetters: 'TF',
    },
    {
        countryEn: 'Gabon',
        countryRu: 'Габон',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1545255,
        capitalEn: 'Libreville',
        capitalRu: 'Либревиль',
        regionCode: 2,
        countryCode: 266,
        countryCodeLetters: 'GA',
    },
    {
        countryEn: 'Gambia',
        countryRu: 'Гамбия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1593256,
        capitalEn: 'Banjul',
        capitalRu: 'Банжул',
        regionCode: 2,
        countryCode: 270,
        countryCodeLetters: 'GM',
    },
    {
        countryEn: 'Georgia',
        countryRu: 'Грузия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 4630000,
        capitalEn: 'Tbilisi',
        capitalRu: 'Тбилиси',
        regionCode: 142,
        countryCode: 268,
        countryCodeLetters: 'GE',
    },
    {
        countryEn: 'Germany',
        countryRu: 'Германия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 81802257,
        capitalEn: 'Berlin',
        capitalRu: 'Берлин',
        regionCode: 150,
        countryCode: 276,
        countryCodeLetters: 'DE',
    },
    {
        countryEn: 'Ghana',
        countryRu: 'Гана',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 24339838,
        capitalEn: 'Accra',
        capitalRu: 'Аккра',
        regionCode: 2,
        countryCode: 288,
        countryCodeLetters: 'GH',
    },
    {
        countryEn: 'Gibraltar',
        countryRu: 'Гибралтар',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 27884,
        capitalEn: 'Gibraltar',
        capitalRu: 'Гибралтар',
        regionCode: 150,
        countryCode: 292,
        countryCodeLetters: 'GI',
    },
    {
        countryEn: 'Greece',
        countryRu: 'Греция',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 11000000,
        capitalEn: 'Athens',
        capitalRu: 'Афины',
        regionCode: 150,
        countryCode: 300,
        countryCodeLetters: 'GR',
    },
    {
        countryEn: 'Greenland',
        countryRu: 'Гренландия',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 56375,
        capitalEn: 'Nuuk',
        capitalRu: 'Нуук',
        regionCode: 19,
        countryCode: 304,
        countryCodeLetters: 'GL',
    },
    {
        countryEn: 'Grenada',
        countryRu: 'Гренада',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 107818,
        capitalEn: "St. George's",
        capitalRu: 'Сент-Джордж',
        regionCode: 19,
        countryCode: 308,
        countryCodeLetters: 'GD',
    },
    {
        countryEn: 'Guadeloupe',
        countryRu: 'Гваделупа',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 443000,
        capitalEn: 'Basse-Terre',
        capitalRu: 'Бас-Тер',
        regionCode: 19,
        countryCode: 312,
        countryCodeLetters: 'GP',
    },
    {
        countryEn: 'Guam',
        countryRu: 'Гуам',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 159358,
        capitalEn: 'Hagåtña',
        capitalRu: 'Хагатна',
        regionCode: 9,
        countryCode: 316,
        countryCodeLetters: 'GU',
    },
    {
        countryEn: 'Guatemala',
        countryRu: 'Гватемала',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 13550440,
        capitalEn: 'Guatemala City',
        capitalRu: 'город Гватемала',
        regionCode: 19,
        countryCode: 320,
        countryCodeLetters: 'GT',
    },
    {
        countryEn: 'Guernsey',
        countryRu: 'Гернси',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 65228,
        capitalEn: 'St Peter Port',
        capitalRu: 'Сент-Питер-Порт',
        regionCode: 150,
        countryCode: 831,
        countryCodeLetters: 'GG',
    },
    {
        countryEn: 'Guinea',
        countryRu: 'Гвинея',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 10324025,
        capitalEn: 'Conakry',
        capitalRu: 'Конакри',
        regionCode: 2,
        countryCode: 324,
        countryCodeLetters: 'GN',
    },
    {
        countryEn: 'Guinea-Bissau',
        countryRu: 'Гвинея-Бисау',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1565126,
        capitalEn: 'Bissau',
        capitalRu: 'Бисау',
        regionCode: 2,
        countryCode: 624,
        countryCodeLetters: 'GW',
    },
    {
        countryEn: 'Guyana',
        countryRu: 'Гайана',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 748486,
        capitalEn: 'Georgetown',
        capitalRu: 'Джорджтаун',
        regionCode: 19,
        countryCode: 328,
        countryCodeLetters: 'GY',
    },
    {
        countryEn: 'Haiti',
        countryRu: 'Гаити',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 9648924,
        capitalEn: 'Port-au-Prince',
        capitalRu: 'Порт-о-Пренс',
        regionCode: 19,
        countryCode: 332,
        countryCodeLetters: 'HT',
    },
    {
        countryEn: 'Heard & McDonald Islands',
        countryRu: 'Острова Херд и Макдональдс',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 0,
        capitalEn: '',
        capitalRu: '',
        regionCode: 9,
        countryCode: 334,
        countryCodeLetters: 'HM',
    },
    {
        countryEn: 'Vatican City',
        countryRu: 'Ватикан',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 921,
        capitalEn: 'Vatican City',
        capitalRu: 'Ватикан',
        regionCode: 150,
        countryCode: 336,
        countryCodeLetters: 'VA',
    },
    {
        countryEn: 'Honduras',
        countryRu: 'Гондурас',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 7989415,
        capitalEn: 'Tegucigalpa',
        capitalRu: 'Тегусигальпа',
        regionCode: 19,
        countryCode: 340,
        countryCodeLetters: 'HN',
    },
    {
        countryEn: 'Hong Kong SAR China',
        countryRu: 'САР Гонконг Китай',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 6898686,
        capitalEn: 'Hong Kong',
        capitalRu: 'Гонконг',
        regionCode: 142,
        countryCode: 344,
        countryCodeLetters: 'HK',
    },
    {
        countryEn: 'Hungary',
        countryRu: 'Венгрия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 9982000,
        capitalEn: 'Budapest',
        capitalRu: 'Будапешт',
        regionCode: 150,
        countryCode: 348,
        countryCodeLetters: 'HU',
    },
    {
        countryEn: 'Iceland',
        countryRu: 'Исландия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 308910,
        capitalEn: 'Reykjavik',
        capitalRu: 'Рейкьявик',
        regionCode: 150,
        countryCode: 352,
        countryCodeLetters: 'IS',
    },
    {
        countryEn: 'India',
        countryRu: 'Индия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 1173108018,
        capitalEn: 'New Delhi',
        capitalRu: 'Нью-Дели',
        regionCode: 142,
        countryCode: 356,
        countryCodeLetters: 'IN',
    },
    {
        countryEn: 'Indonesia',
        countryRu: 'Индонезия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 242968342,
        capitalEn: 'Jakarta',
        capitalRu: 'Джакарта',
        regionCode: 142,
        countryCode: 360,
        countryCodeLetters: 'ID',
    },
    {
        countryEn: 'Iran',
        countryRu: 'Иран',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 76923300,
        capitalEn: 'Tehran',
        capitalRu: 'Тегеран',
        regionCode: 142,
        countryCode: 364,
        countryCodeLetters: 'IR',
    },
    {
        countryEn: 'Iraq',
        countryRu: 'Ирак',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 29671605,
        capitalEn: 'Baghdad',
        capitalRu: 'Багдад',
        regionCode: 142,
        countryCode: 368,
        countryCodeLetters: 'IQ',
    },
    {
        countryEn: 'Ireland',
        countryRu: 'Ирландия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 4622917,
        capitalEn: 'Dublin',
        capitalRu: 'Дублин',
        regionCode: 150,
        countryCode: 372,
        countryCodeLetters: 'IE',
    },
    {
        countryEn: 'Isle of Man',
        countryRu: 'Остров Мэн',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 75049,
        capitalEn: 'Douglas',
        capitalRu: 'Дуглас',
        regionCode: 150,
        countryCode: 833,
        countryCodeLetters: 'IM',
    },
    {
        countryEn: 'Israel',
        countryRu: 'Израиль',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 7353985,
        capitalEn: 'Jerusalem',
        capitalRu: 'Иерусалим',
        regionCode: 142,
        countryCode: 376,
        countryCodeLetters: 'IL',
    },
    {
        countryEn: 'Italy',
        countryRu: 'Италия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 60340328,
        capitalEn: 'Rome',
        capitalRu: 'Рим',
        regionCode: 150,
        countryCode: 380,
        countryCodeLetters: 'IT',
    },
    {
        countryEn: 'Jamaica',
        countryRu: 'Ямайка',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 2847232,
        capitalEn: 'Kingston',
        capitalRu: 'Кингстон',
        regionCode: 19,
        countryCode: 388,
        countryCodeLetters: 'JM',
    },
    {
        countryEn: 'Japan',
        countryRu: 'Япония',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 127288000,
        capitalEn: 'Tokyo',
        capitalRu: 'Токио',
        regionCode: 142,
        countryCode: 392,
        countryCodeLetters: 'JP',
    },
    {
        countryEn: 'Jersey',
        countryRu: 'Джерси',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 90812,
        capitalEn: 'Saint Helier',
        capitalRu: 'Сент-Хелиер',
        regionCode: 150,
        countryCode: 832,
        countryCodeLetters: 'JE',
    },
    {
        countryEn: 'Jordan',
        countryRu: 'Иордания',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 6407085,
        capitalEn: 'Amman',
        capitalRu: 'Амман',
        regionCode: 142,
        countryCode: 400,
        countryCodeLetters: 'JO',
    },
    {
        countryEn: 'Kazakhstan',
        countryRu: 'Казахстан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 15340000,
        capitalEn: 'Nur-Sultan',
        capitalRu: 'Нур-Султан',
        regionCode: 142,
        countryCode: 398,
        countryCodeLetters: 'KZ',
    },
    {
        countryEn: 'Kenya',
        countryRu: 'Кения',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 40046566,
        capitalEn: 'Nairobi',
        capitalRu: 'Найроби',
        regionCode: 2,
        countryCode: 404,
        countryCodeLetters: 'KE',
    },
    {
        countryEn: 'Kiribati',
        countryRu: 'Кирибати',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 92533,
        capitalEn: 'Tarawa',
        capitalRu: 'Тарава',
        regionCode: 9,
        countryCode: 296,
        countryCodeLetters: 'KI',
    },
    {
        countryEn: 'North Korea',
        countryRu: 'Северная Корея',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 22912177,
        capitalEn: 'Pyongyang',
        capitalRu: 'Пхеньян',
        regionCode: 142,
        countryCode: 408,
        countryCodeLetters: 'KP',
    },
    {
        countryEn: 'South Korea',
        countryRu: 'Южная Корея',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 48422644,
        capitalEn: 'Seoul',
        capitalRu: 'Сеул',
        regionCode: 142,
        countryCode: 410,
        countryCodeLetters: 'KR',
    },
    {
        countryEn: 'Kuwait',
        countryRu: 'Кувейт',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 2789132,
        capitalEn: 'Kuwait City',
        capitalRu: 'Кувейт',
        regionCode: 142,
        countryCode: 414,
        countryCodeLetters: 'KW',
    },
    {
        countryEn: 'Kyrgyzstan',
        countryRu: 'Кыргызстан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 5776500,
        capitalEn: 'Bishkek',
        capitalRu: 'Бишкек',
        regionCode: 142,
        countryCode: 417,
        countryCodeLetters: 'KG',
    },
    {
        countryEn: 'Laos',
        countryRu: 'Лаос',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 6368162,
        capitalEn: 'Vientiane',
        capitalRu: 'Вьентьян',
        regionCode: 142,
        countryCode: 418,
        countryCodeLetters: 'LA',
    },
    {
        countryEn: 'Latvia',
        countryRu: 'Латвия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2217969,
        capitalEn: 'Riga',
        capitalRu: 'Рига',
        regionCode: 150,
        countryCode: 428,
        countryCodeLetters: 'LV',
    },
    {
        countryEn: 'Lebanon',
        countryRu: 'Ливан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 4125247,
        capitalEn: 'Beirut',
        capitalRu: 'Бейрут',
        regionCode: 142,
        countryCode: 422,
        countryCodeLetters: 'LB',
    },
    {
        countryEn: 'Lesotho',
        countryRu: 'Лесото',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1919552,
        capitalEn: 'Maseru',
        capitalRu: 'Масеру',
        regionCode: 2,
        countryCode: 426,
        countryCodeLetters: 'LS',
    },
    {
        countryEn: 'Liberia',
        countryRu: 'Либерия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 3685076,
        capitalEn: 'Monrovia',
        capitalRu: 'Монровия',
        regionCode: 2,
        countryCode: 430,
        countryCodeLetters: 'LR',
    },
    {
        countryEn: 'Libya',
        countryRu: 'Ливия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 6461454,
        capitalEn: 'Tripoli',
        capitalRu: 'Триполи',
        regionCode: 2,
        countryCode: 434,
        countryCodeLetters: 'LY',
    },
    {
        countryEn: 'Liechtenstein',
        countryRu: 'Лихтенштейн',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 35000,
        capitalEn: 'Vaduz',
        capitalRu: 'Вадуц',
        regionCode: 150,
        countryCode: 438,
        countryCodeLetters: 'LI',
    },
    {
        countryEn: 'Lithuania',
        countryRu: 'Литва',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2944459,
        capitalEn: 'Vilnius',
        capitalRu: 'Вильнюс',
        regionCode: 150,
        countryCode: 440,
        countryCodeLetters: 'LT',
    },
    {
        countryEn: 'Luxembourg',
        countryRu: 'Люксембург',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 497538,
        capitalEn: 'Luxembourg',
        capitalRu: 'Люксембург',
        regionCode: 150,
        countryCode: 442,
        countryCodeLetters: 'LU',
    },
    {
        countryEn: 'Macao SAR China',
        countryRu: 'САР Макао Китай',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 449198,
        capitalEn: 'Macao',
        capitalRu: 'Макао',
        regionCode: 142,
        countryCode: 446,
        countryCodeLetters: 'MO',
    },
    {
        countryEn: 'Madagascar',
        countryRu: 'Мадагаскар',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 21281844,
        capitalEn: 'Antananarivo',
        capitalRu: 'Антананариву',
        regionCode: 2,
        countryCode: 450,
        countryCodeLetters: 'MG',
    },
    {
        countryEn: 'Malawi',
        countryRu: 'Малави',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 17563749,
        capitalEn: 'Lilongwe',
        capitalRu: 'Лилонгве',
        regionCode: 2,
        countryCode: 454,
        countryCodeLetters: 'MW',
    },
    {
        countryEn: 'Malaysia',
        countryRu: 'Малайзия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 28274729,
        capitalEn: 'Kuala Lumpur',
        capitalRu: 'Куала-Лумпур',
        regionCode: 142,
        countryCode: 458,
        countryCodeLetters: 'MY',
    },
    {
        countryEn: 'Maldives',
        countryRu: 'Мальдивы',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 395650,
        capitalEn: 'Malé',
        capitalRu: 'Мужской',
        regionCode: 142,
        countryCode: 462,
        countryCodeLetters: 'MV',
    },
    {
        countryEn: 'Mali',
        countryRu: 'Мали',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 13796354,
        capitalEn: 'Bamako',
        capitalRu: 'Бамако',
        regionCode: 2,
        countryCode: 466,
        countryCodeLetters: 'ML',
    },
    {
        countryEn: 'Malta',
        countryRu: 'Мальта',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 403000,
        capitalEn: 'Valletta',
        capitalRu: 'Валлетта',
        regionCode: 150,
        countryCode: 470,
        countryCodeLetters: 'MT',
    },
    {
        countryEn: 'Marshall Islands',
        countryRu: 'Маршалловы острова',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 65859,
        capitalEn: 'Majuro',
        capitalRu: 'Маджуро',
        regionCode: 9,
        countryCode: 584,
        countryCodeLetters: 'MH',
    },
    {
        countryEn: 'Martinique',
        countryRu: 'Мартиника',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 432900,
        capitalEn: 'Fort-de-France',
        capitalRu: 'Фор-де-Франс',
        regionCode: 19,
        countryCode: 474,
        countryCodeLetters: 'MQ',
    },
    {
        countryEn: 'Mauritania',
        countryRu: 'Мавритания',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 3205060,
        capitalEn: 'Nouakchott',
        capitalRu: 'Нуакшот',
        regionCode: 2,
        countryCode: 478,
        countryCodeLetters: 'MR',
    },
    {
        countryEn: 'Mauritius',
        countryRu: 'Маврикий',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1294104,
        capitalEn: 'Port Louis',
        capitalRu: 'Порт-Луи',
        regionCode: 2,
        countryCode: 480,
        countryCodeLetters: 'MU',
    },
    {
        countryEn: 'Mayotte',
        countryRu: 'Майотта',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 159042,
        capitalEn: 'Mamoudzou',
        capitalRu: 'Мамудзу',
        regionCode: 2,
        countryCode: 175,
        countryCodeLetters: 'YT',
    },
    {
        countryEn: 'Mexico',
        countryRu: 'Мексика',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 112468855,
        capitalEn: 'Mexico City',
        capitalRu: 'Мехико',
        regionCode: 19,
        countryCode: 484,
        countryCodeLetters: 'MX',
    },
    {
        countryEn: 'Micronesia',
        countryRu: 'Микронезия',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 107708,
        capitalEn: 'Palikir',
        capitalRu: 'Паликир',
        regionCode: 9,
        countryCode: 583,
        countryCodeLetters: 'FM',
    },
    {
        countryEn: 'Moldova',
        countryRu: 'Молдова',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 4324000,
        capitalEn: 'Chișinău',
        capitalRu: 'Кишинев',
        regionCode: 150,
        countryCode: 498,
        countryCodeLetters: 'MD',
    },
    {
        countryEn: 'Monaco',
        countryRu: 'Монако',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 32965,
        capitalEn: 'Monaco',
        capitalRu: 'Монако',
        regionCode: 150,
        countryCode: 492,
        countryCodeLetters: 'MC',
    },
    {
        countryEn: 'Mongolia',
        countryRu: 'Монголия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 3086918,
        capitalEn: 'Ulaanbaatar',
        capitalRu: 'Улан-Батор',
        regionCode: 142,
        countryCode: 496,
        countryCodeLetters: 'MN',
    },
    {
        countryEn: 'Montenegro',
        countryRu: 'Черногория',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 666730,
        capitalEn: 'Podgorica',
        capitalRu: 'Подгорица',
        regionCode: 150,
        countryCode: 499,
        countryCodeLetters: 'ME',
    },
    {
        countryEn: 'Montserrat',
        countryRu: 'Монтсеррат',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 9341,
        capitalEn: 'Plymouth',
        capitalRu: 'Плимут',
        regionCode: 19,
        countryCode: 500,
        countryCodeLetters: 'MS',
    },
    {
        countryEn: 'Morocco',
        countryRu: 'Марокко',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 33848242,
        capitalEn: 'Rabat',
        capitalRu: 'Рабат',
        regionCode: 2,
        countryCode: 504,
        countryCodeLetters: 'MA',
    },
    {
        countryEn: 'Mozambique',
        countryRu: 'Мозамбик',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 22061451,
        capitalEn: 'Maputo',
        capitalRu: 'Мапуту',
        regionCode: 2,
        countryCode: 508,
        countryCodeLetters: 'MZ',
    },
    {
        countryEn: 'Myanmar (Burma)',
        countryRu: 'Мьянма (Бирма)',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 53414374,
        capitalEn: 'Nay Pyi Taw',
        capitalRu: 'Най Пьи Тау',
        regionCode: 142,
        countryCode: 104,
        countryCodeLetters: 'MM',
    },
    {
        countryEn: 'Namibia',
        countryRu: 'Намибия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 2128471,
        capitalEn: 'Windhoek',
        capitalRu: 'Виндхук',
        regionCode: 2,
        countryCode: 516,
        countryCodeLetters: 'NA',
    },
    {
        countryEn: 'Nauru',
        countryRu: 'Науру',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 10065,
        capitalEn: 'Yaren District',
        capitalRu: 'Яренский район',
        regionCode: 9,
        countryCode: 520,
        countryCodeLetters: 'NR',
    },
    {
        countryEn: 'Nepal',
        countryRu: 'Непал',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 28951852,
        capitalEn: 'Kathmandu',
        capitalRu: 'Катманду',
        regionCode: 142,
        countryCode: 524,
        countryCodeLetters: 'NP',
    },
    {
        countryEn: 'Netherlands',
        countryRu: 'Нидерланды',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 16645000,
        capitalEn: 'Amsterdam',
        capitalRu: 'Амстердам',
        regionCode: 150,
        countryCode: 528,
        countryCodeLetters: 'NL',
    },
    {
        countryEn: 'New Caledonia',
        countryRu: 'Новая Каледония',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 216494,
        capitalEn: 'Noumea',
        capitalRu: 'Нумеа',
        regionCode: 9,
        countryCode: 540,
        countryCodeLetters: 'NC',
    },
    {
        countryEn: 'New Zealand',
        countryRu: 'Новая Зеландия',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 4252277,
        capitalEn: 'Wellington',
        capitalRu: 'Веллингтон',
        regionCode: 9,
        countryCode: 554,
        countryCodeLetters: 'NZ',
    },
    {
        countryEn: 'Nicaragua',
        countryRu: 'Никарагуа',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 5995928,
        capitalEn: 'Managua',
        capitalRu: 'Манагуа',
        regionCode: 19,
        countryCode: 558,
        countryCodeLetters: 'NI',
    },
    {
        countryEn: 'Niger',
        countryRu: 'Нигер',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 15878271,
        capitalEn: 'Niamey',
        capitalRu: 'Ниамей',
        regionCode: 2,
        countryCode: 562,
        countryCodeLetters: 'NE',
    },
    {
        countryEn: 'Nigeria',
        countryRu: 'Нигерия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 154000000,
        capitalEn: 'Abuja',
        capitalRu: 'Абуджа',
        regionCode: 2,
        countryCode: 566,
        countryCodeLetters: 'NG',
    },
    {
        countryEn: 'Niue',
        countryRu: 'Ниуэ',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 2166,
        capitalEn: 'Alofi',
        capitalRu: 'Алофи',
        regionCode: 9,
        countryCode: 570,
        countryCodeLetters: 'NU',
    },
    {
        countryEn: 'Norfolk Island',
        countryRu: 'Остров Норфолк',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 1828,
        capitalEn: 'Kingston',
        capitalRu: 'Кингстон',
        regionCode: 9,
        countryCode: 574,
        countryCodeLetters: 'NF',
    },
    {
        countryEn: 'North Macedonia',
        countryRu: 'Северная Македония',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2062294,
        capitalEn: 'Skopje',
        capitalRu: 'Скопье',
        regionCode: 150,
        countryCode: 807,
        countryCodeLetters: 'MK',
    },
    {
        countryEn: 'Northern Mariana Islands',
        countryRu: 'Северные Марианские острова',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 53883,
        capitalEn: 'Saipan',
        capitalRu: 'Сайпан',
        regionCode: 9,
        countryCode: 580,
        countryCodeLetters: 'MP',
    },
    {
        countryEn: 'Norway',
        countryRu: 'Норвегия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 5009150,
        capitalEn: 'Oslo',
        capitalRu: 'Осло',
        regionCode: 150,
        countryCode: 578,
        countryCodeLetters: 'NO',
    },
    {
        countryEn: 'Oman',
        countryRu: 'Оман',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 2967717,
        capitalEn: 'Muscat',
        capitalRu: 'Мускат',
        regionCode: 142,
        countryCode: 512,
        countryCodeLetters: 'OM',
    },
    {
        countryEn: 'Pakistan',
        countryRu: 'Пакистан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 184404791,
        capitalEn: 'Islamabad',
        capitalRu: 'Исламабад',
        regionCode: 142,
        countryCode: 586,
        countryCodeLetters: 'PK',
    },
    {
        countryEn: 'Palau',
        countryRu: 'Палау',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 19907,
        capitalEn: 'Ngerulmud',
        capitalRu: 'Нгерулмуд',
        regionCode: 9,
        countryCode: 585,
        countryCodeLetters: 'PW',
    },
    {
        countryEn: 'Palestinian Territories',
        countryRu: 'территории Палестины',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 3800000,
        capitalEn: '',
        capitalRu: '',
        regionCode: 142,
        countryCode: 275,
        countryCodeLetters: 'PS',
    },
    {
        countryEn: 'Panama',
        countryRu: 'Панама',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 3410676,
        capitalEn: 'Panama City',
        capitalRu: 'Панама',
        regionCode: 19,
        countryCode: 591,
        countryCodeLetters: 'PA',
    },
    {
        countryEn: 'Papua New Guinea',
        countryRu: 'Папуа - Новая Гвинея',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 6064515,
        capitalEn: 'Port Moresby',
        capitalRu: 'Порт-Морсби',
        regionCode: 9,
        countryCode: 598,
        countryCodeLetters: 'PG',
    },
    {
        countryEn: 'Paraguay',
        countryRu: 'Парагвай',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 6375830,
        capitalEn: 'Asunción',
        capitalRu: 'Асунсьон',
        regionCode: 19,
        countryCode: 600,
        countryCodeLetters: 'PY',
    },
    {
        countryEn: 'Peru',
        countryRu: 'Перу',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 29907003,
        capitalEn: 'Lima',
        capitalRu: 'Лима',
        regionCode: 19,
        countryCode: 604,
        countryCodeLetters: 'PE',
    },
    {
        countryEn: 'Philippines',
        countryRu: 'Филиппины',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 99900177,
        capitalEn: 'Manila',
        capitalRu: 'Манила',
        regionCode: 142,
        countryCode: 608,
        countryCodeLetters: 'PH',
    },
    {
        countryEn: 'Pitcairn Islands',
        countryRu: 'Острова Питкэрн',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 46,
        capitalEn: 'Adamstown',
        capitalRu: 'Адамстаун',
        regionCode: 9,
        countryCode: 612,
        countryCodeLetters: 'PN',
    },
    {
        countryEn: 'Poland',
        countryRu: 'Польша',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 38500000,
        capitalEn: 'Warsaw',
        capitalRu: 'Варшава',
        regionCode: 150,
        countryCode: 616,
        countryCodeLetters: 'PL',
    },
    {
        countryEn: 'Portugal',
        countryRu: 'Португалия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 10676000,
        capitalEn: 'Lisbon',
        capitalRu: 'Лиссабон',
        regionCode: 150,
        countryCode: 620,
        countryCodeLetters: 'PT',
    },
    {
        countryEn: 'Puerto Rico',
        countryRu: 'Пуэрто-Рико',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 3916632,
        capitalEn: 'San Juan',
        capitalRu: 'Сан-Хуан',
        regionCode: 19,
        countryCode: 630,
        countryCodeLetters: 'PR',
    },
    {
        countryEn: 'Qatar',
        countryRu: 'Катар',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 840926,
        capitalEn: 'Doha',
        capitalRu: 'Доха',
        regionCode: 142,
        countryCode: 634,
        countryCodeLetters: 'QA',
    },
    {
        countryEn: 'Réunion',
        countryRu: 'Реюньон',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 776948,
        capitalEn: 'Saint-Denis',
        capitalRu: 'Сен-Дени',
        regionCode: 2,
        countryCode: 638,
        countryCodeLetters: 'RE',
    },
    {
        countryEn: 'Romania',
        countryRu: 'Румыния',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 21959278,
        capitalEn: 'Bucharest',
        capitalRu: 'Бухарест',
        regionCode: 150,
        countryCode: 642,
        countryCodeLetters: 'RO',
    },
    {
        countryEn: 'Russia',
        countryRu: 'Россия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 140702000,
        capitalEn: 'Moscow',
        capitalRu: 'Москва',
        regionCode: 150,
        countryCode: 643,
        countryCodeLetters: 'RU',
    },
    {
        countryEn: 'Rwanda',
        countryRu: 'Руанда',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 11055976,
        capitalEn: 'Kigali',
        capitalRu: 'Кигали',
        regionCode: 2,
        countryCode: 646,
        countryCodeLetters: 'RW',
    },
    {
        countryEn: 'St. Barthélemy',
        countryRu: 'Сен-Бартельми',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 8450,
        capitalEn: 'Gustavia',
        capitalRu: 'Густавия',
        regionCode: 19,
        countryCode: 652,
        countryCodeLetters: 'BL',
    },
    {
        countryEn: 'St. Helena',
        countryRu: 'Святая Елена',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 7460,
        capitalEn: 'Jamestown',
        capitalRu: 'Джеймстаун',
        regionCode: 2,
        countryCode: 654,
        countryCodeLetters: 'SH',
    },
    {
        countryEn: 'St. Kitts & Nevis',
        countryRu: 'Сент-Китс и Невис',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 51134,
        capitalEn: 'Basseterre',
        capitalRu: 'Бастер',
        regionCode: 19,
        countryCode: 659,
        countryCodeLetters: 'KN',
    },
    {
        countryEn: 'St. Lucia',
        countryRu: 'Сент-Люсия',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 160922,
        capitalEn: 'Castries',
        capitalRu: 'Кастри',
        regionCode: 19,
        countryCode: 662,
        countryCodeLetters: 'LC',
    },
    {
        countryEn: 'St. Martin',
        countryRu: 'Святой Мартин',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 35925,
        capitalEn: 'Marigot',
        capitalRu: 'Мариго',
        regionCode: 19,
        countryCode: 663,
        countryCodeLetters: 'MF',
    },
    {
        countryEn: 'St. Pierre & Miquelon',
        countryRu: 'Сен-Пьер и Микелон',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 7012,
        capitalEn: 'Saint-Pierre',
        capitalRu: 'Сен-Пьер',
        regionCode: 19,
        countryCode: 666,
        countryCodeLetters: 'PM',
    },
    {
        countryEn: 'St. Vincent & Grenadines',
        countryRu: 'Сент-Винсент и Гренадины',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 104217,
        capitalEn: 'Kingstown',
        capitalRu: 'Кингстаун',
        regionCode: 19,
        countryCode: 670,
        countryCodeLetters: 'VC',
    },
    {
        countryEn: 'Samoa',
        countryRu: 'Самоа',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 192001,
        capitalEn: 'Apia',
        capitalRu: 'Апиа',
        regionCode: 9,
        countryCode: 882,
        countryCodeLetters: 'WS',
    },
    {
        countryEn: 'San Marino',
        countryRu: 'Сан-Марино',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 31477,
        capitalEn: 'San Marino',
        capitalRu: 'Сан-Марино',
        regionCode: 150,
        countryCode: 674,
        countryCodeLetters: 'SM',
    },
    {
        countryEn: 'São Tomé & Príncipe',
        countryRu: 'Сан-Томе и Принсипи',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 197700,
        capitalEn: 'São Tomé',
        capitalRu: 'Сан-Томе',
        regionCode: 2,
        countryCode: 678,
        countryCodeLetters: 'ST',
    },
    {
        countryEn: 'Saudi Arabia',
        countryRu: 'Саудовская Аравия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 25731776,
        capitalEn: 'Riyadh',
        capitalRu: 'Эр-Рияд',
        regionCode: 142,
        countryCode: 682,
        countryCodeLetters: 'SA',
    },
    {
        countryEn: 'Senegal',
        countryRu: 'Сенегал',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 12323252,
        capitalEn: 'Dakar',
        capitalRu: 'Дакар',
        regionCode: 2,
        countryCode: 686,
        countryCodeLetters: 'SN',
    },
    {
        countryEn: 'Serbia',
        countryRu: 'Сербия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 7344847,
        capitalEn: 'Belgrade',
        capitalRu: 'Белград',
        regionCode: 150,
        countryCode: 688,
        countryCodeLetters: 'RS',
    },
    {
        countryEn: 'Seychelles',
        countryRu: 'Сейшелы',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 88340,
        capitalEn: 'Victoria',
        capitalRu: 'Виктория',
        regionCode: 2,
        countryCode: 690,
        countryCodeLetters: 'SC',
    },
    {
        countryEn: 'Sierra Leone',
        countryRu: 'Сьерра-Леоне',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 5245695,
        capitalEn: 'Freetown',
        capitalRu: 'Фритаун',
        regionCode: 2,
        countryCode: 694,
        countryCodeLetters: 'SL',
    },
    {
        countryEn: 'Singapore',
        countryRu: 'Сингапур',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 4701069,
        capitalEn: 'Singapore',
        capitalRu: 'Сингапур',
        regionCode: 142,
        countryCode: 702,
        countryCodeLetters: 'SG',
    },
    {
        countryEn: 'Sint Maarten',
        countryRu: 'Синт-Мартен',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 37429,
        capitalEn: 'Philipsburg',
        capitalRu: 'Филипсбург',
        regionCode: 19,
        countryCode: 534,
        countryCodeLetters: 'SX',
    },
    {
        countryEn: 'Slovakia',
        countryRu: 'Словакия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 5455000,
        capitalEn: 'Bratislava',
        capitalRu: 'Братислава',
        regionCode: 150,
        countryCode: 703,
        countryCodeLetters: 'SK',
    },
    {
        countryEn: 'Slovenia',
        countryRu: 'Словения',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2007000,
        capitalEn: 'Ljubljana',
        capitalRu: 'Любляна',
        regionCode: 150,
        countryCode: 705,
        countryCodeLetters: 'SI',
    },
    {
        countryEn: 'Solomon Islands',
        countryRu: 'Соломоновы острова',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 559198,
        capitalEn: 'Honiara',
        capitalRu: 'Хониара',
        regionCode: 9,
        countryCode: 90,
        countryCodeLetters: 'SB',
    },
    {
        countryEn: 'Somalia',
        countryRu: 'Сомали',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 10112453,
        capitalEn: 'Mogadishu',
        capitalRu: 'Могадишо',
        regionCode: 2,
        countryCode: 706,
        countryCodeLetters: 'SO',
    },
    {
        countryEn: 'South Africa',
        countryRu: 'Южная Африка',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 49000000,
        capitalEn: 'Pretoria',
        capitalRu: 'Претория',
        regionCode: 2,
        countryCode: 710,
        countryCodeLetters: 'ZA',
    },
    {
        countryEn: 'South Georgia & South Sandwich Islands',
        countryRu: 'Южная Георгия и Южные Сандвичевы острова',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 30,
        capitalEn: 'Grytviken',
        capitalRu: 'Грютвикен',
        regionCode: 19,
        countryCode: 239,
        countryCodeLetters: 'GS',
    },
    {
        countryEn: 'South Sudan',
        countryRu: 'южный Судан',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 8260490,
        capitalEn: 'Juba',
        capitalRu: 'Джуба',
        regionCode: 2,
        countryCode: 728,
        countryCodeLetters: 'SS',
    },
    {
        countryEn: 'Spain',
        countryRu: 'Испания',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 46505963,
        capitalEn: 'Madrid',
        capitalRu: 'Мадрид',
        regionCode: 150,
        countryCode: 724,
        countryCodeLetters: 'ES',
    },
    {
        countryEn: 'Sri Lanka',
        countryRu: 'Шри-Ланка',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 21513990,
        capitalEn: 'Colombo',
        capitalRu: 'Коломбо',
        regionCode: 142,
        countryCode: 144,
        countryCodeLetters: 'LK',
    },
    {
        countryEn: 'Sudan',
        countryRu: 'Судан',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 35000000,
        capitalEn: 'Khartoum',
        capitalRu: 'Хартум',
        regionCode: 2,
        countryCode: 729,
        countryCodeLetters: 'SD',
    },
    {
        countryEn: 'Suriname',
        countryRu: 'Суринам',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 492829,
        capitalEn: 'Paramaribo',
        capitalRu: 'Парамарибо',
        regionCode: 19,
        countryCode: 740,
        countryCodeLetters: 'SR',
    },
    {
        countryEn: 'Svalbard & Jan Mayen',
        countryRu: 'Шпицберген и Ян-Майен',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2550,
        capitalEn: 'Longyearbyen',
        capitalRu: 'Лонгйир',
        regionCode: 150,
        countryCode: 744,
        countryCodeLetters: 'SJ',
    },
    {
        countryEn: 'Sweden',
        countryRu: 'Швеция',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 9828655,
        capitalEn: 'Stockholm',
        capitalRu: 'Стокгольм',
        regionCode: 150,
        countryCode: 752,
        countryCodeLetters: 'SE',
    },
    {
        countryEn: 'Switzerland',
        countryRu: 'Швейцария',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 8484100,
        capitalEn: 'Bern',
        capitalRu: 'Берн',
        regionCode: 150,
        countryCode: 756,
        countryCodeLetters: 'CH',
    },
    {
        countryEn: 'Syria',
        countryRu: 'Сирия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 22198110,
        capitalEn: 'Damascus',
        capitalRu: 'Дамаск',
        regionCode: 142,
        countryCode: 760,
        countryCodeLetters: 'SY',
    },
    {
        countryEn: 'Taiwan',
        countryRu: 'Тайвань',
        regionEn: '',
        regionRu: '',
        population: 22894384,
        capitalEn: 'Taipei',
        capitalRu: 'Тайбэй',
        regionCode: '',
        countryCode: 158,
        countryCodeLetters: 'TW',
    },
    {
        countryEn: 'Tajikistan',
        countryRu: 'Таджикистан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 7487489,
        capitalEn: 'Dushanbe',
        capitalRu: 'Душанбе',
        regionCode: 142,
        countryCode: 762,
        countryCodeLetters: 'TJ',
    },
    {
        countryEn: 'Tanzania',
        countryRu: 'Танзания',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 41892895,
        capitalEn: 'Dodoma',
        capitalRu: 'Додома',
        regionCode: 2,
        countryCode: 834,
        countryCodeLetters: 'TZ',
    },
    {
        countryEn: 'Thailand',
        countryRu: 'Таиланд',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 67089500,
        capitalEn: 'Bangkok',
        capitalRu: 'Бангкок',
        regionCode: 142,
        countryCode: 764,
        countryCodeLetters: 'TH',
    },
    {
        countryEn: 'Timor-Leste',
        countryRu: 'Тимор-Лешти',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 1154625,
        capitalEn: 'Dili',
        capitalRu: 'Дили',
        regionCode: 142,
        countryCode: 626,
        countryCodeLetters: 'TL',
    },
    {
        countryEn: 'Togo',
        countryRu: 'Идти',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 6587239,
        capitalEn: 'Lomé',
        capitalRu: 'Ломе',
        regionCode: 2,
        countryCode: 768,
        countryCodeLetters: 'TG',
    },
    {
        countryEn: 'Tokelau',
        countryRu: 'Токелау',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 1466,
        capitalEn: '',
        capitalRu: '',
        regionCode: 9,
        countryCode: 772,
        countryCodeLetters: 'TK',
    },
    {
        countryEn: 'Tonga',
        countryRu: 'Тонга',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 122580,
        capitalEn: "Nuku'alofa",
        capitalRu: 'Нукуалофа',
        regionCode: 9,
        countryCode: 776,
        countryCodeLetters: 'TO',
    },
    {
        countryEn: 'Trinidad & Tobago',
        countryRu: 'Тринидад и Тобаго',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 1328019,
        capitalEn: 'Port of Spain',
        capitalRu: 'Порт-оф-Спейн',
        regionCode: 19,
        countryCode: 780,
        countryCodeLetters: 'TT',
    },
    {
        countryEn: 'Tunisia',
        countryRu: 'Тунис',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 10589025,
        capitalEn: 'Tunis',
        capitalRu: 'Тунис',
        regionCode: 2,
        countryCode: 788,
        countryCodeLetters: 'TN',
    },
    {
        countryEn: 'Turkey',
        countryRu: 'Турция',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 77804122,
        capitalEn: 'Ankara',
        capitalRu: 'Анкара',
        regionCode: 142,
        countryCode: 792,
        countryCodeLetters: 'TR',
    },
    {
        countryEn: 'Turkmenistan',
        countryRu: 'Туркменистан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 4940916,
        capitalEn: 'Ashgabat',
        capitalRu: 'Ашхабад',
        regionCode: 142,
        countryCode: 795,
        countryCodeLetters: 'TM',
    },
    {
        countryEn: 'Turks & Caicos Islands',
        countryRu: 'Теркс и Кайкос',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 20556,
        capitalEn: 'Cockburn Town',
        capitalRu: 'Кокберн Таун',
        regionCode: 19,
        countryCode: 796,
        countryCodeLetters: 'TC',
    },
    {
        countryEn: 'Tuvalu',
        countryRu: 'Тувалу',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 10472,
        capitalEn: 'Funafuti',
        capitalRu: 'Фунафути',
        regionCode: 9,
        countryCode: 798,
        countryCodeLetters: 'TV',
    },
    {
        countryEn: 'Uganda',
        countryRu: 'Уганда',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 33398682,
        capitalEn: 'Kampala',
        capitalRu: 'Кампала',
        regionCode: 2,
        countryCode: 800,
        countryCodeLetters: 'UG',
    },
    {
        countryEn: 'Ukraine',
        countryRu: 'Украина',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 45415596,
        capitalEn: 'Kyiv',
        capitalRu: 'Киев',
        regionCode: 150,
        countryCode: 804,
        countryCodeLetters: 'UA',
    },
    {
        countryEn: 'United Arab Emirates',
        countryRu: 'Объединенные Арабские Эмираты',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 4975593,
        capitalEn: 'Abu Dhabi',
        capitalRu: 'Абу Даби',
        regionCode: 142,
        countryCode: 784,
        countryCodeLetters: 'AE',
    },
    {
        countryEn: 'United Kingdom',
        countryRu: 'Великобритания',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 62348447,
        capitalEn: 'London',
        capitalRu: 'Лондон',
        regionCode: 150,
        countryCode: 826,
        countryCodeLetters: 'GB',
    },
    {
        countryEn: 'United States',
        countryRu: 'Соединенные Штаты',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 310232863,
        capitalEn: 'Washington',
        capitalRu: 'Вашингтон',
        regionCode: 19,
        countryCode: 840,
        countryCodeLetters: 'US',
    },
    {
        countryEn: 'U.S. Outlying Islands',
        countryRu: 'Отдалённые острова США',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 0,
        capitalEn: '',
        capitalRu: '',
        regionCode: 9,
        countryCode: 581,
        countryCodeLetters: 'UM',
    },
    {
        countryEn: 'Uruguay',
        countryRu: 'Уругвай',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 3477000,
        capitalEn: 'Montevideo',
        capitalRu: 'Монтевидео',
        regionCode: 19,
        countryCode: 858,
        countryCodeLetters: 'UY',
    },
    {
        countryEn: 'Uzbekistan',
        countryRu: 'Узбекистан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 27865738,
        capitalEn: 'Tashkent',
        capitalRu: 'Ташкент',
        regionCode: 142,
        countryCode: 860,
        countryCodeLetters: 'UZ',
    },
    {
        countryEn: 'Vanuatu',
        countryRu: 'Вануату',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 221552,
        capitalEn: 'Port Vila',
        capitalRu: 'Порт-Вила',
        regionCode: 9,
        countryCode: 548,
        countryCodeLetters: 'VU',
    },
    {
        countryEn: 'Venezuela',
        countryRu: 'Венесуэла',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 27223228,
        capitalEn: 'Caracas',
        capitalRu: 'Каракас',
        regionCode: 19,
        countryCode: 862,
        countryCodeLetters: 'VE',
    },
    {
        countryEn: 'Vietnam',
        countryRu: 'Вьетнам',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 89571130,
        capitalEn: 'Hanoi',
        capitalRu: 'Ханой',
        regionCode: 142,
        countryCode: 704,
        countryCodeLetters: 'VN',
    },
    {
        countryEn: 'British Virgin Islands',
        countryRu: 'Британские Виргинские острова',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 21730,
        capitalEn: 'Road Town',
        capitalRu: 'Роад Таун',
        regionCode: 19,
        countryCode: 92,
        countryCodeLetters: 'VG',
    },
    {
        countryEn: 'U.S. Virgin Islands',
        countryRu: 'Виргинские острова США',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 108708,
        capitalEn: 'Charlotte Amalie',
        capitalRu: 'Шарлотта Амалия',
        regionCode: 19,
        countryCode: 850,
        countryCodeLetters: 'VI',
    },
    {
        countryEn: 'Wallis & Futuna',
        countryRu: 'Уоллис и Футуна',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 16025,
        capitalEn: 'Mata-Utu',
        capitalRu: 'Мата-Уту',
        regionCode: 9,
        countryCode: 876,
        countryCodeLetters: 'WF',
    },
    {
        countryEn: 'Western Sahara',
        countryRu: 'Западная Сахара',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 273008,
        capitalEn: '',
        capitalRu: '',
        regionCode: 2,
        countryCode: 732,
        countryCodeLetters: 'EH',
    },
    {
        countryEn: 'Yemen',
        countryRu: 'Йемен',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 23495361,
        capitalEn: 'Sanaa',
        capitalRu: 'Сана',
        regionCode: 142,
        countryCode: 887,
        countryCodeLetters: 'YE',
    },
    {
        countryEn: 'Zambia',
        countryRu: 'Замбия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 13460305,
        capitalEn: 'Lusaka',
        capitalRu: 'Лусака',
        regionCode: 2,
        countryCode: 894,
        countryCodeLetters: 'ZM',
    },
    {
        countryEn: 'Zimbabwe',
        countryRu: 'Зимбабве',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 13061000,
        capitalEn: 'Harare',
        capitalRu: 'Хараре',
        regionCode: 2,
        countryCode: 716,
        countryCodeLetters: 'ZW',
    },
];

export const africa = world.filter((el) => el.regionEn === 'Africa');
export const asia = world.filter((el) => el.regionEn === 'Asia');
export const oceania = world.filter((el) => el.regionEn === 'Oceania');
export const america = world.filter((el) => el.regionEn === 'America');
export const europe = world.filter((el) => el.regionEn === 'Europe');
