export const world = [
    {
        countryEn: 'Vanuatu',
        countryRu: 'Вануату',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 221552,
        capitalEn: 'Port Vila',
        capitalRu: 'Порт-Вила',
        regionCode: '009',
        countryCode: 548,
        countryCodeLetters: 'VU',
        area: 12200,
    },
    {
        countryEn: 'Montenegro',
        countryRu: 'Черногория',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 666730,
        capitalEn: 'Podgorica',
        capitalRu: 'Подгорица',
        regionCode: '150',
        countryCode: 499,
        countryCodeLetters: 'ME',
        area: 14026,
    },
    {
        countryEn: 'Fiji',
        countryRu: 'Фиджи',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 875983,
        capitalEn: 'Suva',
        capitalRu: 'Сува',
        regionCode: '009',
        countryCode: 242,
        countryCodeLetters: 'FJ',
        area: 18270,
    },
    {
        countryEn: 'New Caledonia',
        countryRu: 'Новая Каледония',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 216494,
        capitalEn: 'Noumea',
        capitalRu: 'Нумеа',
        regionCode: '009',
        countryCode: 540,
        countryCodeLetters: 'NC',
        area: 19060,
    },
    {
        countryEn: 'Slovenia',
        countryRu: 'Словения',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2007000,
        capitalEn: 'Ljubljana',
        capitalRu: 'Любляна',
        regionCode: '150',
        countryCode: 705,
        countryCodeLetters: 'SI',
        area: 20273,
    },
    {
        countryEn: 'Israel',
        countryRu: 'Израиль',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 7353985,
        capitalEn: 'Jerusalem',
        capitalRu: 'Иерусалим',
        regionCode: '142',
        countryCode: 376,
        countryCodeLetters: 'IL',
        area: 20770,
    },
    {
        countryEn: 'Djibouti',
        countryRu: 'Джибути',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 740528,
        capitalEn: 'Djibouti',
        capitalRu: 'Джибути',
        regionCode: '002',
        countryCode: 262,
        countryCodeLetters: 'DJ',
        area: 23000,
    },
    {
        countryEn: 'Macedonia (the former Yugoslav Republic of)',
        countryRu: 'Северная Македония',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2062294,
        capitalEn: 'Skopje',
        capitalRu: 'Скопье',
        regionCode: '150',
        countryCode: 807,
        countryCodeLetters: 'MK',
        area: 25333,
    },
    {
        countryEn: 'Rwanda',
        countryRu: 'Руанда',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 11055976,
        capitalEn: 'Kigali',
        capitalRu: 'Кигали',
        regionCode: '002',
        countryCode: 646,
        countryCodeLetters: 'RW',
        area: 26338,
    },
    {
        countryEn: 'Burundi',
        countryRu: 'Бурунди',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 9863117,
        capitalEn: 'Gitega',
        capitalRu: 'Гитега',
        regionCode: '002',
        countryCode: 108,
        countryCodeLetters: 'BI',
        area: 27830,
    },
    {
        countryEn: 'Equatorial Guinea',
        countryRu: 'Экваториальная Гвинея',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1014999,
        capitalEn: 'Malabo',
        capitalRu: 'Малабо',
        regionCode: '002',
        countryCode: 226,
        countryCodeLetters: 'GQ',
        area: 28051,
    },
    {
        countryEn: 'Solomon Islands',
        countryRu: 'Соломоновы острова',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 559198,
        capitalEn: 'Honiara',
        capitalRu: 'Хониара',
        regionCode: '009',
        countryCode: 90,
        countryCodeLetters: 'SB',
        area: 28450,
    },
    {
        countryEn: 'Albania',
        countryRu: 'Албания',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2986952,
        capitalEn: 'Tirana',
        capitalRu: 'Тирана',
        regionCode: '150',
        countryCode: 8,
        countryCodeLetters: 'AL',
        area: 28748,
    },
    {
        countryEn: 'Armenia',
        countryRu: 'Армения',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 2968000,
        capitalEn: 'Yerevan',
        capitalRu: 'Ереван',
        regionCode: '142',
        countryCode: 51,
        countryCodeLetters: 'AM',
        area: 29800,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/am.svg)',
    },
    {
        countryEn: 'Lesotho',
        countryRu: 'Лесото',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1919552,
        capitalEn: 'Maseru',
        capitalRu: 'Масеру',
        regionCode: '002',
        countryCode: 426,
        countryCodeLetters: 'LS',
        area: 30355,
    },
    {
        countryEn: 'Belgium',
        countryRu: 'Бельгия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 10403000,
        capitalEn: 'Brussels',
        capitalRu: 'Брюссель',
        regionCode: '150',
        countryCode: 56,
        countryCodeLetters: 'BE',
        area: 30510,
    },
    {
        countryEn: 'Moldova (Republic of)',
        countryRu: 'Молдова',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 4324000,
        capitalEn: 'Chișinău',
        capitalRu: 'Кишинев',
        regionCode: '150',
        countryCode: 498,
        countryCodeLetters: 'MD',
        area: 33843,
    },
    {
        countryEn: 'Taiwan',
        countryRu: 'Тайвань',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 22894384,
        capitalEn: 'Taipei',
        capitalRu: 'Тайбэй',
        regionCode: '142',
        countryCode: 158,
        countryCodeLetters: 'TW',
        area: 35980,
    },
    {
        countryEn: 'Guinea-Bissau',
        countryRu: 'Гвинея-Бисау',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1565126,
        capitalEn: 'Bissau',
        capitalRu: 'Бисау',
        regionCode: '002',
        countryCode: 624,
        countryCodeLetters: 'GW',
        area: 36120,
    },
    {
        countryEn: 'Switzerland',
        countryRu: 'Швейцария',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 8484100,
        capitalEn: 'Bern',
        capitalRu: 'Берн',
        regionCode: '150',
        countryCode: 756,
        countryCodeLetters: 'CH',
        area: 41290,
    },
    {
        countryEn: 'Netherlands',
        countryRu: 'Нидерланды',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 16645000,
        capitalEn: 'Amsterdam',
        capitalRu: 'Амстердам',
        regionCode: '150',
        countryCode: 528,
        countryCodeLetters: 'NL',
        area: 41526,
    },
    {
        countryEn: 'Denmark',
        countryRu: 'Дания',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 5484000,
        capitalEn: 'Copenhagen',
        capitalRu: 'Копенгаген',
        regionCode: '150',
        countryCode: 208,
        countryCodeLetters: 'DK',
        area: 43094,
    },
    {
        countryEn: 'Gibraltar',
        countryRu: 'Гибралтар',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 27884,
        capitalEn: 'Gibraltar',
        capitalRu: 'Гибралтар',
        regionCode: '150',
        countryCode: 292,
        countryCodeLetters: 'GI',
        area: 45052,
    },
    {
        countryEn: 'Estonia',
        countryRu: 'Эстония',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 1291170,
        capitalEn: 'Tallinn',
        capitalRu: 'Таллинн',
        regionCode: '150',
        countryCode: 233,
        countryCodeLetters: 'EE',
        area: 45226,
    },
    {
        countryEn: 'Bhutan',
        countryRu: 'Бутан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 699847,
        capitalEn: 'Thimphu',
        capitalRu: 'Тхимпху',
        regionCode: '142',
        countryCode: 64,
        countryCodeLetters: 'BT',
        area: 47000,
    },
    {
        countryEn: 'Dominican Republic',
        countryRu: 'Доминиканская Республика',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 9823821,
        capitalEn: 'Santo Domingo',
        capitalRu: 'Санто-Доминго',
        regionCode: '019',
        countryCode: 214,
        countryCodeLetters: 'DO',
        area: 48730,
    },
    {
        countryEn: 'Slovakia',
        countryRu: 'Словакия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 5455000,
        capitalEn: 'Bratislava',
        capitalRu: 'Братислава',
        regionCode: '150',
        countryCode: 703,
        countryCodeLetters: 'SK',
        area: 48845,
    },
    {
        countryEn: 'Costa Rica',
        countryRu: 'Коста-Рика',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 4516220,
        capitalEn: 'San José',
        capitalRu: 'Сан - Хосе',
        regionCode: '019',
        countryCode: 188,
        countryCodeLetters: 'CR',
        area: 51100,
    },
    {
        countryEn: 'Bosnia and Herzegovina',
        countryRu: 'Босния и Герцеговина',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 4590000,
        capitalEn: 'Sarajevo',
        capitalRu: 'Сараево',
        regionCode: '150',
        countryCode: 70,
        countryCodeLetters: 'BA',
        area: 51129,
    },
    {
        countryEn: 'Croatia',
        countryRu: 'Хорватия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 4284889,
        capitalEn: 'Zagreb',
        capitalRu: 'Загреб',
        regionCode: '150',
        countryCode: 191,
        countryCodeLetters: 'HR',
        area: 56542,
    },
    {
        countryEn: 'Togo',
        countryRu: 'Того',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 6587239,
        capitalEn: 'Lomé',
        capitalRu: 'Ломе',
        regionCode: '002',
        countryCode: 768,
        countryCodeLetters: 'TG',
        area: 56785,
    },
    {
        countryEn: 'Svalbard and Jan Mayen',
        countryRu: 'Шпицберген и Ян-Майен',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2550,
        capitalEn: 'Longyearbyen',
        capitalRu: 'Лонгйир',
        regionCode: '150',
        countryCode: 744,
        countryCodeLetters: 'SJ',
        area: 62049,
    },
    {
        countryEn: 'Latvia',
        countryRu: 'Латвия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2217969,
        capitalEn: 'Riga',
        capitalRu: 'Рига',
        regionCode: '150',
        countryCode: 428,
        countryCodeLetters: 'LV',
        area: 64589,
    },
    {
        countryEn: 'Lithuania',
        countryRu: 'Литва',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 2944459,
        capitalEn: 'Vilnius',
        capitalRu: 'Вильнюс',
        regionCode: '150',
        countryCode: 440,
        countryCodeLetters: 'LT',
        area: 65200,
    },
    {
        countryEn: 'Sri Lanka',
        countryRu: 'Шри-Ланка',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 21513990,
        capitalEn: 'Colombo',
        capitalRu: 'Коломбо',
        regionCode: '142',
        countryCode: 144,
        countryCodeLetters: 'LK',
        area: 65610,
    },
    {
        countryEn: 'Georgia',
        countryRu: 'Грузия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 4630000,
        capitalEn: 'Tbilisi',
        capitalRu: 'Тбилиси',
        regionCode: '142',
        countryCode: 268,
        countryCodeLetters: 'GE',
        area: 69700,
    },
    {
        countryEn: 'Ireland',
        countryRu: 'Ирландия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 4622917,
        capitalEn: 'Dublin',
        capitalRu: 'Дублин',
        regionCode: '150',
        countryCode: 372,
        countryCodeLetters: 'IE',
        area: 70280,
    },
    {
        countryEn: 'Sierra Leone',
        countryRu: 'Сьерра-Леоне',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 5245695,
        capitalEn: 'Freetown',
        capitalRu: 'Фритаун',
        regionCode: '002',
        countryCode: 694,
        countryCodeLetters: 'SL',
        area: 71740,
    },
    {
        countryEn: 'Panama',
        countryRu: 'Панама',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 3410676,
        capitalEn: 'Panama City',
        capitalRu: 'Панама',
        regionCode: '019',
        countryCode: 591,
        countryCodeLetters: 'PA',
        area: 78200,
    },
    {
        countryEn: 'Czechia',
        countryRu: 'Чехия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 10476000,
        capitalEn: 'Prague',
        capitalRu: 'Прага',
        regionCode: '150',
        countryCode: 203,
        countryCodeLetters: 'CZ',
        area: 78866,
    },
    {
        countryEn: 'United Arab Emirates',
        countryRu: 'Объединенные Арабские Эмираты',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 4975593,
        capitalEn: 'Abu Dhabi',
        capitalRu: 'Абу Даби',
        regionCode: '142',
        countryCode: 784,
        countryCodeLetters: 'AE',
        area: 82880,
    },
    {
        countryEn: 'Austria',
        countryRu: 'Австрия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 8205000,
        capitalEn: 'Vienna',
        capitalRu: 'Вена',
        regionCode: '150',
        countryCode: 40,
        countryCodeLetters: 'AT',
        area: 83858,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/at.svg)',
    },
    {
        countryEn: 'Azerbaijan',
        countryRu: 'Азербайджан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 8303512,
        capitalEn: 'Baku',
        capitalRu: 'Баку',
        regionCode: '142',
        countryCode: 31,
        countryCodeLetters: 'AZ',
        area: 86600,
    },
    {
        countryEn: 'Serbia',
        countryRu: 'Сербия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 7344847,
        capitalEn: 'Belgrade',
        capitalRu: 'Белград',
        regionCode: '150',
        countryCode: 688,
        countryCodeLetters: 'RS',
        area: 88361,
    },
    {
        countryEn: 'French Guiana',
        countryRu: 'Французская Гвиана',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 195506,
        capitalEn: 'Cayenne',
        capitalRu: 'Кайенна',
        regionCode: '019',
        countryCode: 254,
        countryCodeLetters: 'GF',
        area: 91000,
    },
    {
        countryEn: 'Jordan',
        countryRu: 'Иордания',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 6407085,
        capitalEn: 'Amman',
        capitalRu: 'Амман',
        regionCode: '142',
        countryCode: 400,
        countryCodeLetters: 'JO',
        area: 92300,
    },
    {
        countryEn: 'Portugal',
        countryRu: 'Португалия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 10676000,
        capitalEn: 'Lisbon',
        capitalRu: 'Лиссабон',
        regionCode: '150',
        countryCode: 620,
        countryCodeLetters: 'PT',
        area: 92391,
    },
    {
        countryEn: 'Hungary',
        countryRu: 'Венгрия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 9982000,
        capitalEn: 'Budapest',
        capitalRu: 'Будапешт',
        regionCode: '150',
        countryCode: 348,
        countryCodeLetters: 'HU',
        area: 93030,
    },
    {
        countryEn: 'Korea (Republic of)',
        countryRu: 'Южная Корея',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 48422644,
        capitalEn: 'Seoul',
        capitalRu: 'Сеул',
        regionCode: '142',
        countryCode: 410,
        countryCodeLetters: 'KR',
        area: 98480,
    },
    {
        countryEn: 'Iceland',
        countryRu: 'Исландия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 308910,
        capitalEn: 'Reykjavik',
        capitalRu: 'Рейкьявик',
        regionCode: '150',
        countryCode: 352,
        countryCodeLetters: 'IS',
        area: 103000,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/is.svg)',
    },
    {
        countryEn: 'Guatemala',
        countryRu: 'Гватемала',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 13550440,
        capitalEn: 'Guatemala City',
        capitalRu: 'город Гватемала',
        regionCode: '019',
        countryCode: 320,
        countryCodeLetters: 'GT',
        area: 108890,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/gt.svg)',
    },
    {
        countryEn: 'Cuba',
        countryRu: 'Куба',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 11423000,
        capitalEn: 'Havana',
        capitalRu: 'Гавана',
        regionCode: '019',
        countryCode: 192,
        countryCodeLetters: 'CU',
        area: 110860,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/cu.svg)',
    },
    {
        countryEn: 'Bulgaria',
        countryRu: 'Болгария',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 7000039,
        capitalEn: 'Sofia',
        capitalRu: 'София',
        regionCode: '150',
        countryCode: 100,
        countryCodeLetters: 'BG',
        area: 110910,
    },
    {
        countryEn: 'Liberia',
        countryRu: 'Либерия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 3685076,
        capitalEn: 'Monrovia',
        capitalRu: 'Монровия',
        regionCode: '002',
        countryCode: 430,
        countryCodeLetters: 'LR',
        area: 111370,
    },
    {
        countryEn: 'Honduras',
        countryRu: 'Гондурас',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 7989415,
        capitalEn: 'Tegucigalpa',
        capitalRu: 'Тегусигальпа',
        regionCode: '019',
        countryCode: 340,
        countryCodeLetters: 'HN',
        area: 112090,
    },
    {
        countryEn: 'Benin',
        countryRu: 'Бенин',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 9056010,
        capitalEn: 'Porto-Novo',
        capitalRu: 'Порто-Ново',
        regionCode: '002',
        countryCode: 204,
        countryCodeLetters: 'BJ',
        area: 112620,
    },
    {
        countryEn: 'Malawi',
        countryRu: 'Малави',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 17563749,
        capitalEn: 'Lilongwe',
        capitalRu: 'Лилонгве',
        regionCode: '002',
        countryCode: 454,
        countryCodeLetters: 'MW',
        area: 118480,
    },
    {
        countryEn: 'Korea (Democratic People\\s Republic of)',
        countryRu: 'Северная Корея',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 22912177,
        capitalEn: 'Pyongyang',
        capitalRu: 'Пхеньян',
        regionCode: '142',
        countryCode: 408,
        countryCodeLetters: 'KP',
        area: 120540,
    },
    {
        countryEn: 'Eritrea',
        countryRu: 'Эритрея',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 5792984,
        capitalEn: 'Asmara',
        capitalRu: 'Асмэра',
        regionCode: '002',
        countryCode: 232,
        countryCodeLetters: 'ER',
        area: 121320,
    },
    {
        countryEn: 'Nicaragua',
        countryRu: 'Никарагуа',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 5995928,
        capitalEn: 'Managua',
        capitalRu: 'Манагуа',
        regionCode: '019',
        countryCode: 558,
        countryCodeLetters: 'NI',
        area: 129494,
    },
    {
        countryEn: 'Greece',
        countryRu: 'Греция',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 11000000,
        capitalEn: 'Athens',
        capitalRu: 'Афины',
        regionCode: '150',
        countryCode: 300,
        countryCodeLetters: 'GR',
        area: 131940,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/gr.svg)',
    },
    {
        countryEn: 'Nepal',
        countryRu: 'Непал',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 28951852,
        capitalEn: 'Kathmandu',
        capitalRu: 'Катманду',
        regionCode: '142',
        countryCode: 524,
        countryCodeLetters: 'NP',
        area: 140800,
    },
    {
        countryEn: 'Tajikistan',
        countryRu: 'Таджикистан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 7487489,
        capitalEn: 'Dushanbe',
        capitalRu: 'Душанбе',
        regionCode: '142',
        countryCode: 762,
        countryCodeLetters: 'TJ',
        area: 143100,
    },
    {
        countryEn: 'Bangladesh',
        countryRu: 'Бангладеш',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 156118464,
        capitalEn: 'Dhaka',
        capitalRu: 'Дакка',
        regionCode: '142',
        countryCode: 50,
        countryCodeLetters: 'BD',
        area: 144000,
    },
    {
        countryEn: 'Suriname',
        countryRu: 'Суринам',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 492829,
        capitalEn: 'Paramaribo',
        capitalRu: 'Парамарибо',
        regionCode: '019',
        countryCode: 740,
        countryCodeLetters: 'SR',
        area: 163270,
    },
    {
        countryEn: 'Tunisia',
        countryRu: 'Тунис',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 10589025,
        capitalEn: 'Tunis',
        capitalRu: 'Тунис',
        regionCode: '002',
        countryCode: 788,
        countryCodeLetters: 'TN',
        area: 163610,
    },
    {
        countryEn: 'Uruguay',
        countryRu: 'Уругвай',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 3477000,
        capitalEn: 'Montevideo',
        capitalRu: 'Монтевидео',
        regionCode: '019',
        countryCode: 858,
        countryCodeLetters: 'UY',
        area: 176220,
    },
    {
        countryEn: 'Cambodia',
        countryRu: 'Камбоджа',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 14453680,
        capitalEn: 'Phnom Penh',
        capitalRu: 'Пномпень',
        regionCode: '142',
        countryCode: 116,
        countryCodeLetters: 'KH',
        area: 181040,
    },
    {
        countryEn: 'Syrian Arab Republic',
        countryRu: 'Сирия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 22198110,
        capitalEn: 'Damascus',
        capitalRu: 'Дамаск',
        regionCode: '142',
        countryCode: 760,
        countryCodeLetters: 'SY',
        area: 185180,
    },
    {
        countryEn: 'Senegal',
        countryRu: 'Сенегал',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 12323252,
        capitalEn: 'Dakar',
        capitalRu: 'Дакар',
        regionCode: '002',
        countryCode: 686,
        countryCodeLetters: 'SN',
        area: 196190,
    },
    {
        countryEn: 'Kyrgyzstan',
        countryRu: 'Кыргызстан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 5776500,
        capitalEn: 'Bishkek',
        capitalRu: 'Бишкек',
        regionCode: '142',
        countryCode: 417,
        countryCodeLetters: 'KG',
        area: 198500,
    },
    {
        countryEn: 'Belarus',
        countryRu: 'Беларусь',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 9685000,
        capitalEn: 'Minsk',
        capitalRu: 'Минск',
        regionCode: '150',
        countryCode: 112,
        countryCodeLetters: 'BY',
        area: 207600,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/by.svg)',
    },
    {
        countryEn: 'Oman',
        countryRu: 'Оман',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 2967717,
        capitalEn: 'Muscat',
        capitalRu: 'Мускат',
        regionCode: '142',
        countryCode: 512,
        countryCodeLetters: 'OM',
        area: 212460,
    },
    {
        countryEn: 'Guyana',
        countryRu: 'Гайана',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 748486,
        capitalEn: 'Georgetown',
        capitalRu: 'Джорджтаун',
        regionCode: '019',
        countryCode: 328,
        countryCodeLetters: 'GY',
        area: 214970,
    },
    {
        countryEn: 'Uganda',
        countryRu: 'Уганда',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 33398682,
        capitalEn: 'Kampala',
        capitalRu: 'Кампала',
        regionCode: '002',
        countryCode: 800,
        countryCodeLetters: 'UG',
        area: 236040,
    },
    {
        countryEn: "Lao People\\'s Democratic Republic",
        countryRu: 'Лаос',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 6368162,
        capitalEn: 'Vientiane',
        capitalRu: 'Вьентьян',
        regionCode: '142',
        countryCode: 418,
        countryCodeLetters: 'LA',
        area: 236800,
    },
    {
        countryEn: 'Romania',
        countryRu: 'Румыния',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 21959278,
        capitalEn: 'Bucharest',
        capitalRu: 'Бухарест',
        regionCode: '150',
        countryCode: 642,
        countryCodeLetters: 'RO',
        area: 237500,
    },
    {
        countryEn: 'Ghana',
        countryRu: 'Гана',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 24339838,
        capitalEn: 'Accra',
        capitalRu: 'Аккра',
        regionCode: '002',
        countryCode: 288,
        countryCodeLetters: 'GH',
        area: 239460,
    },
    {
        countryEn: 'United Kingdom of Great Britain and Northern Ireland',
        countryRu: 'Великобритания',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 62348447,
        capitalEn: 'London',
        capitalRu: 'Лондон',
        regionCode: '150',
        countryCode: 826,
        countryCodeLetters: 'GB',
        area: 244820,
    },
    {
        countryEn: 'Guinea',
        countryRu: 'Гвинея',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 10324025,
        capitalEn: 'Conakry',
        capitalRu: 'Конакри',
        regionCode: '002',
        countryCode: 324,
        countryCodeLetters: 'GN',
        area: 245857,
    },
    {
        countryEn: 'Western Sahara',
        countryRu: 'Западная Сахара',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 273008,
        capitalEn: 'El Aaiun',
        capitalRu: 'Эль-Аюн',
        regionCode: '002',
        countryCode: 732,
        countryCodeLetters: 'EH',
        area: 266000,
    },
    {
        countryEn: 'Gabon',
        countryRu: 'Габон',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 1545255,
        capitalEn: 'Libreville',
        capitalRu: 'Либревиль',
        regionCode: '002',
        countryCode: 266,
        countryCodeLetters: 'GA',
        area: 267667,
    },
    {
        countryEn: 'New Zealand',
        countryRu: 'Новая Зеландия',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 4252277,
        capitalEn: 'Wellington',
        capitalRu: 'Веллингтон',
        regionCode: '009',
        countryCode: 554,
        countryCodeLetters: 'NZ',
        area: 268680,
        flag: 'https://flagicons.lipis.dev/flags/4x3/nz.svg',
    },
    {
        countryEn: 'Burkina Faso',
        countryRu: 'Буркина-Фасо',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 16241811,
        capitalEn: 'Ouagadougou',
        capitalRu: 'Уагадугу',
        regionCode: '002',
        countryCode: 854,
        countryCodeLetters: 'BF',
        area: 274200,
    },
    {
        countryEn: 'Ecuador',
        countryRu: 'Эквадор',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 14790608,
        capitalEn: 'Quito',
        capitalRu: 'Кито',
        regionCode: '019',
        countryCode: 218,
        countryCodeLetters: 'EC',
        area: 283560,
    },
    {
        countryEn: 'Philippines',
        countryRu: 'Филиппины',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 99900177,
        capitalEn: 'Manila',
        capitalRu: 'Манила',
        regionCode: '142',
        countryCode: 608,
        countryCodeLetters: 'PH',
        area: 300000,
    },
    {
        countryEn: 'Italy',
        countryRu: 'Италия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 60340328,
        capitalEn: 'Rome',
        capitalRu: 'Рим',
        regionCode: '150',
        countryCode: 380,
        countryCodeLetters: 'IT',
        area: 301230,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/it.svg)',
    },
    {
        countryEn: 'Poland',
        countryRu: 'Польша',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 38500000,
        capitalEn: 'Warsaw',
        capitalRu: 'Варшава',
        regionCode: '150',
        countryCode: 616,
        countryCodeLetters: 'PL',
        area: 312685,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/pl.svg)',
    },
    {
        countryEn: "Côte d\\'Ivoire",
        countryRu: 'Берег Слоновой Кости',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 21058798,
        capitalEn: 'Yamoussoukro',
        capitalRu: 'Ямусукро',
        regionCode: '002',
        countryCode: 384,
        countryCodeLetters: 'CI',
        area: 322460,
    },
    {
        countryEn: 'Norway',
        countryRu: 'Норвегия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 5009150,
        capitalEn: 'Oslo',
        capitalRu: 'Осло',
        regionCode: '150',
        countryCode: 578,
        countryCodeLetters: 'NO',
        area: 324220,
    },
    {
        countryEn: 'Viet Nam',
        countryRu: 'Вьетнам',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 89571130,
        capitalEn: 'Hanoi',
        capitalRu: 'Ханой',
        regionCode: '142',
        countryCode: 704,
        countryCodeLetters: 'VN',
        area: 329560,
    },
    {
        countryEn: 'Malaysia',
        countryRu: 'Малайзия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 28274729,
        capitalEn: 'Kuala Lumpur',
        capitalRu: 'Куала-Лумпур',
        regionCode: '142',
        countryCode: 458,
        countryCodeLetters: 'MY',
        area: 329750,
    },
    {
        countryEn: 'Finland',
        countryRu: 'Финляндия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 5244000,
        capitalEn: 'Helsinki',
        capitalRu: 'Хельсинки',
        regionCode: '150',
        countryCode: 246,
        countryCodeLetters: 'FI',
        area: 337030,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/fi.svg)',
    },
    {
        countryEn: 'Congo',
        countryRu: 'Конго - Браззавиль',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 3039126,
        capitalEn: 'Brazzaville',
        capitalRu: 'Браззавиль',
        regionCode: '002',
        countryCode: 178,
        countryCodeLetters: 'CG',
        area: 342000,
    },
    {
        countryEn: 'Germany',
        countryRu: 'Германия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 81802257,
        capitalEn: 'Berlin',
        capitalRu: 'Берлин',
        regionCode: '150',
        countryCode: 276,
        countryCodeLetters: 'DE',
        area: 357021,
    },
    {
        countryEn: 'Japan',
        countryRu: 'Япония',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 127288000,
        capitalEn: 'Tokyo',
        capitalRu: 'Токио',
        regionCode: '142',
        countryCode: 392,
        countryCodeLetters: 'JP',
        area: 377835,
    },
    {
        countryEn: 'Zimbabwe',
        countryRu: 'Зимбабве',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 13061000,
        capitalEn: 'Harare',
        capitalRu: 'Хараре',
        regionCode: '002',
        countryCode: 716,
        countryCodeLetters: 'ZW',
        area: 390580,
    },
    {
        countryEn: 'Paraguay',
        countryRu: 'Парагвай',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 6375830,
        capitalEn: 'Asunción',
        capitalRu: 'Асунсьон',
        regionCode: '019',
        countryCode: 600,
        countryCodeLetters: 'PY',
        area: 406750,
    },
    {
        countryEn: 'Iraq',
        countryRu: 'Ирак',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 29671605,
        capitalEn: 'Baghdad',
        capitalRu: 'Багдад',
        regionCode: '142',
        countryCode: 368,
        countryCodeLetters: 'IQ',
        area: 437072,
    },
    {
        countryEn: 'Morocco',
        countryRu: 'Марокко',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 33848242,
        capitalEn: 'Rabat',
        capitalRu: 'Рабат',
        regionCode: '002',
        countryCode: 504,
        countryCodeLetters: 'MA',
        area: 446550,
    },
    {
        countryEn: 'Uzbekistan',
        countryRu: 'Узбекистан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 27865738,
        capitalEn: 'Tashkent',
        capitalRu: 'Ташкент',
        regionCode: '142',
        countryCode: 860,
        countryCodeLetters: 'UZ',
        area: 447400,
    },
    {
        countryEn: 'Sweden',
        countryRu: 'Швеция',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 9828655,
        capitalEn: 'Stockholm',
        capitalRu: 'Стокгольм',
        regionCode: '150',
        countryCode: 752,
        countryCodeLetters: 'SE',
        area: 449964,
    },
    {
        countryEn: 'Papua New Guinea',
        countryRu: 'Папуа - Новая Гвинея',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 6064515,
        capitalEn: 'Port Moresby',
        capitalRu: 'Порт-Морсби',
        regionCode: '009',
        countryCode: 598,
        countryCodeLetters: 'PG',
        area: 462840,
    },
    {
        countryEn: 'Cameroon',
        countryRu: 'Камерун',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 19294149,
        capitalEn: 'Yaoundé',
        capitalRu: 'Яунде',
        regionCode: '002',
        countryCode: 120,
        countryCodeLetters: 'CM',
        area: 475440,
    },
    {
        countryEn: 'Turkmenistan',
        countryRu: 'Туркменистан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 4940916,
        capitalEn: 'Ashgabat',
        capitalRu: 'Ашхабад',
        regionCode: '142',
        countryCode: 795,
        countryCodeLetters: 'TM',
        area: 488100,
    },
    {
        countryEn: 'Spain',
        countryRu: 'Испания',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 46505963,
        capitalEn: 'Madrid',
        capitalRu: 'Мадрид',
        regionCode: '150',
        countryCode: 724,
        countryCodeLetters: 'ES',
        area: 504782,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/es.svg)',
    },
    {
        countryEn: 'Thailand',
        countryRu: 'Таиланд',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 67089500,
        capitalEn: 'Bangkok',
        capitalRu: 'Бангкок',
        regionCode: '142',
        countryCode: 764,
        countryCodeLetters: 'TH',
        area: 514000,
    },
    {
        countryEn: 'Yemen',
        countryRu: 'Йемен',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 23495361,
        capitalEn: 'Sanaa',
        capitalRu: 'Сана',
        regionCode: '142',
        countryCode: 887,
        countryCodeLetters: 'YE',
        area: 527970,
    },
    {
        countryEn: 'France',
        countryRu: 'Франция',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 64768389,
        capitalEn: 'Paris',
        capitalRu: 'Париж',
        regionCode: '150',
        countryCode: 250,
        countryCodeLetters: 'FR',
        area: 547030,
    },
    {
        countryEn: 'Kenya',
        countryRu: 'Кения',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 40046566,
        capitalEn: 'Nairobi',
        capitalRu: 'Найроби',
        regionCode: '002',
        countryCode: 404,
        countryCodeLetters: 'KE',
        area: 582650,
    },
    {
        countryEn: 'Madagascar',
        countryRu: 'Мадагаскар',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 21281844,
        capitalEn: 'Antananarivo',
        capitalRu: 'Антананариву',
        regionCode: '002',
        countryCode: 450,
        countryCodeLetters: 'MG',
        area: 587040,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/mg.svg)',
    },
    {
        countryEn: 'Botswana',
        countryRu: 'Ботсвана',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 2029307,
        capitalEn: 'Gaborone',
        capitalRu: 'Габороне',
        regionCode: '002',
        countryCode: 72,
        countryCodeLetters: 'BW',
        area: 600370,
    },
    {
        countryEn: 'Ukraine',
        countryRu: 'Украина',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 45415596,
        capitalEn: 'Kyiv',
        capitalRu: 'Киев',
        regionCode: '150',
        countryCode: 804,
        countryCodeLetters: 'UA',
        area: 603700,
    },
    {
        countryEn: 'Central African Republic',
        countryRu: 'Центрально-Африканская Республика',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 4844927,
        capitalEn: 'Bangui',
        capitalRu: 'Банги',
        regionCode: '002',
        countryCode: 140,
        countryCodeLetters: 'CF',
        area: 622984,
    },
    {
        countryEn: 'Somalia',
        countryRu: 'Сомали',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 10112453,
        capitalEn: 'Mogadishu',
        capitalRu: 'Могадишо',
        regionCode: '002',
        countryCode: 706,
        countryCodeLetters: 'SO',
        area: 637657,
    },
    {
        countryEn: 'South Sudan',
        countryRu: 'южный Судан',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 8260490,
        capitalEn: 'Juba',
        capitalRu: 'Джуба',
        regionCode: '002',
        countryCode: 728,
        countryCodeLetters: 'SS',
        area: 644329,
    },
    {
        countryEn: 'Afghanistan',
        countryRu: 'Афганистан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 29121286,
        capitalEn: 'Kabul',
        capitalRu: 'Кабул',
        regionCode: '142',
        countryCode: 4,
        countryCodeLetters: 'AF',
        area: 647500,
    },
    {
        countryEn: 'Myanmar',
        countryRu: 'Мьянма (Бирма)',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 53414374,
        capitalEn: 'Nay Pyi Taw',
        capitalRu: 'Най Пьи Тау',
        regionCode: '142',
        countryCode: 104,
        countryCodeLetters: 'MM',
        area: 678500,
    },
    {
        countryEn: 'Zambia',
        countryRu: 'Замбия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 13460305,
        capitalEn: 'Lusaka',
        capitalRu: 'Лусака',
        regionCode: '002',
        countryCode: 894,
        countryCodeLetters: 'ZM',
        area: 752614,
    },
    {
        countryEn: 'Chile',
        countryRu: 'Чили',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 16746491,
        capitalEn: 'Santiago',
        capitalRu: 'Сантьяго',
        regionCode: '019',
        countryCode: 152,
        countryCodeLetters: 'CL',
        area: 756950,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/cl.svg)',
    },
    {
        countryEn: 'Turkey',
        countryRu: 'Турция',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 77804122,
        capitalEn: 'Ankara',
        capitalRu: 'Анкара',
        regionCode: '142',
        countryCode: 792,
        countryCodeLetters: 'TR',
        area: 780580,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/tr.svg)',
    },
    {
        countryEn: 'Mozambique',
        countryRu: 'Мозамбик',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 22061451,
        capitalEn: 'Maputo',
        capitalRu: 'Мапуту',
        regionCode: '002',
        countryCode: 508,
        countryCodeLetters: 'MZ',
        area: 801590,
    },
    {
        countryEn: 'Pakistan',
        countryRu: 'Пакистан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 184404791,
        capitalEn: 'Islamabad',
        capitalRu: 'Исламабад',
        regionCode: '142',
        countryCode: 586,
        countryCodeLetters: 'PK',
        area: 803940,
    },
    {
        countryEn: 'Namibia',
        countryRu: 'Намибия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 2128471,
        capitalEn: 'Windhoek',
        capitalRu: 'Виндхук',
        regionCode: '002',
        countryCode: 516,
        countryCodeLetters: 'NA',
        area: 825418,
    },
    {
        countryEn: 'Venezuela (Bolivarian Republic of)',
        countryRu: 'Венесуэла',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 27223228,
        capitalEn: 'Caracas',
        capitalRu: 'Каракас',
        regionCode: '019',
        countryCode: 862,
        countryCodeLetters: 'VE',
        area: 912050,
    },
    {
        countryEn: 'Nigeria',
        countryRu: 'Нигерия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 154000000,
        capitalEn: 'Abuja',
        capitalRu: 'Абуджа',
        regionCode: '002',
        countryCode: 566,
        countryCodeLetters: 'NG',
        area: 923768,
    },
    {
        countryEn: 'Tanzania, United Republic of',
        countryRu: 'Танзания',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 41892895,
        capitalEn: 'Dodoma',
        capitalRu: 'Додома',
        regionCode: '002',
        countryCode: 834,
        countryCodeLetters: 'TZ',
        area: 945087,
    },
    {
        countryEn: 'Egypt',
        countryRu: 'Египет',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 80471869,
        capitalEn: 'Cairo',
        capitalRu: 'Каир',
        regionCode: '002',
        countryCode: 818,
        countryCodeLetters: 'EG',
        area: 1001450,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/eg.svg)',
    },
    {
        countryEn: 'Mauritania',
        countryRu: 'Мавритания',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 3205060,
        capitalEn: 'Nouakchott',
        capitalRu: 'Нуакшот',
        regionCode: '002',
        countryCode: 478,
        countryCodeLetters: 'MR',
        area: 1030700,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/mr.svg)',
    },
    {
        countryEn: 'Bolivia (Plurinational State of)',
        countryRu: 'Боливия',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 9947418,
        capitalEn: 'Sucre',
        capitalRu: 'Сукре',
        regionCode: '019',
        countryCode: 68,
        countryCodeLetters: 'BO',
        area: 1098580,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/bo.svg)',
    },
    {
        countryEn: 'Ethiopia',
        countryRu: 'Эфиопия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 88013491,
        capitalEn: 'Addis Ababa',
        capitalRu: 'Аддис-Абеба',
        regionCode: '002',
        countryCode: 231,
        countryCodeLetters: 'ET',
        area: 1127127,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/et.svg)',
    },
    {
        countryEn: 'Colombia',
        countryRu: 'Колумбия',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 47790000,
        capitalEn: 'Bogotá',
        capitalRu: 'Богота',
        regionCode: '019',
        countryCode: 170,
        countryCodeLetters: 'CO',
        area: 1138910,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/co.svg)',
    },
    {
        countryEn: 'South Africa',
        countryRu: 'Южная Африка',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 49000000,
        capitalEn: 'Pretoria',
        capitalRu: 'Претория',
        regionCode: '002',
        countryCode: 710,
        countryCodeLetters: 'ZA',
        area: 1219912,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/za.svg)',
    },
    {
        countryEn: 'Mali',
        countryRu: 'Мали',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 13796354,
        capitalEn: 'Bamako',
        capitalRu: 'Бамако',
        regionCode: '002',
        countryCode: 466,
        countryCodeLetters: 'ML',
        area: 1240000,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/ml.svg)',
    },
    {
        countryEn: 'Angola',
        countryRu: 'Ангола',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 13068161,
        capitalEn: 'Luanda',
        capitalRu: 'Луанда',
        regionCode: '002',
        countryCode: 24,
        countryCodeLetters: 'AO',
        area: 1246700,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/ao.svg)',
    },
    {
        countryEn: 'Niger',
        countryRu: 'Нигер',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 15878271,
        capitalEn: 'Niamey',
        capitalRu: 'Ниамей',
        regionCode: '002',
        countryCode: 562,
        countryCodeLetters: 'NE',
        area: 1267000,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/ne.svg)',
    },
    {
        countryEn: 'Chad',
        countryRu: 'Чад',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 10543464,
        capitalEn: "N'Djamena",
        capitalRu: 'Нджамена',
        regionCode: '002',
        countryCode: 148,
        countryCodeLetters: 'TD',
        area: 1284000,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/td.svg)',
    },
    {
        countryEn: 'Peru',
        countryRu: 'Перу',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 29907003,
        capitalEn: 'Lima',
        capitalRu: 'Лима',
        regionCode: '019',
        countryCode: 604,
        countryCodeLetters: 'PE',
        area: 1285220,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/pe.svg)',
    },
    {
        countryEn: 'Mongolia',
        countryRu: 'Монголия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 3086918,
        capitalEn: 'Ulaanbaatar',
        capitalRu: 'Улан-Батор',
        regionCode: '142',
        countryCode: 496,
        countryCodeLetters: 'MN',
        area: 1565000,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/mn.svg)',
    },
    {
        countryEn: 'Iran (Islamic Republic of)',
        countryRu: 'Иран',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 76923300,
        capitalEn: 'Tehran',
        capitalRu: 'Тегеран',
        regionCode: '142',
        countryCode: 364,
        countryCodeLetters: 'IR',
        area: 1648000,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/ir.svg)',
    },
    {
        countryEn: 'Libya',
        countryRu: 'Ливия',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 6461454,
        capitalEn: 'Tripoli',
        capitalRu: 'Триполи',
        regionCode: '002',
        countryCode: 434,
        countryCodeLetters: 'LY',
        area: 1759540,
    },
    {
        countryEn: 'Sudan',
        countryRu: 'Судан',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 35000000,
        capitalEn: 'Khartoum',
        capitalRu: 'Хартум',
        regionCode: '002',
        countryCode: 729,
        countryCodeLetters: 'SD',
        area: 1861484,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/sd.svg)',
    },
    {
        countryEn: 'Indonesia',
        countryRu: 'Индонезия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 242968342,
        capitalEn: 'Jakarta',
        capitalRu: 'Джакарта',
        regionCode: '142',
        countryCode: 360,
        countryCodeLetters: 'ID',
        area: 1919440,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/id.svg)',
    },
    {
        countryEn: 'Saudi Arabia',
        countryRu: 'Саудовская Аравия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 25731776,
        capitalEn: 'Riyadh',
        capitalRu: 'Эр-Рияд',
        regionCode: '142',
        countryCode: 682,
        countryCodeLetters: 'SA',
        area: 1960582,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/sa.svg)',
    },
    {
        countryEn: 'Mexico',
        countryRu: 'Мексика',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 112468855,
        capitalEn: 'Mexico City',
        capitalRu: 'Мехико',
        regionCode: '019',
        countryCode: 484,
        countryCodeLetters: 'MX',
        area: 1972550,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/mx.svg)',
    },
    {
        countryEn: 'Greenland',
        countryRu: 'Гренландия',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 56375,
        capitalEn: 'Nuuk',
        capitalRu: 'Нуук',
        regionCode: '019',
        countryCode: 304,
        countryCodeLetters: 'GL',
        area: 2166086,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/gl.svg)',
    },
    {
        countryEn: 'Congo (Democratic Republic of the)',
        countryRu: 'Конго - Киншаса',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 70916439,
        capitalEn: 'Kinshasa',
        capitalRu: 'Киншаса',
        regionCode: '002',
        countryCode: 180,
        countryCodeLetters: 'CD',
        area: 2345410,
    },
    {
        countryEn: 'Algeria',
        countryRu: 'Алжир',
        regionEn: 'Africa',
        regionRu: 'Африка',
        population: 34586184,
        capitalEn: 'Algiers',
        capitalRu: 'Алжир',
        regionCode: '002',
        countryCode: 12,
        countryCodeLetters: 'DZ',
        area: 2381740,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/dz.svg)',
    },
    {
        countryEn: 'Kazakhstan',
        countryRu: 'Казахстан',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 15340000,
        capitalEn: 'Nur-Sultan',
        capitalRu: 'Нур-Султан',
        regionCode: '142',
        countryCode: 398,
        countryCodeLetters: 'KZ',
        area: 2717300,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/kz.svg)',
    },
    {
        countryEn: 'Argentina',
        countryRu: 'Аргентина',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 41343201,
        capitalEn: 'Buenos Aires',
        capitalRu: 'Буэнос айрес',
        regionCode: '019',
        countryCode: 32,
        countryCodeLetters: 'AR',
        area: 2766890,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/ar.svg)',
    },
    {
        countryEn: 'India',
        countryRu: 'Индия',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 1173108018,
        capitalEn: 'New Delhi',
        capitalRu: 'Нью-Дели',
        regionCode: '142',
        countryCode: 356,
        countryCodeLetters: 'IN',
        area: 3287590,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/in.svg)',
    },
    {
        countryEn: 'Australia',
        countryRu: 'Австралия',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 21515754,
        capitalEn: 'Canberra',
        capitalRu: 'Канберра',
        regionCode: '009',
        countryCode: 36,
        countryCodeLetters: 'AU',
        area: 7686850,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/au.svg)',
    },
    {
        countryEn: 'Brazil',
        countryRu: 'Бразилия',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 201103330,
        capitalEn: 'Brasília',
        capitalRu: 'Бразилиа',
        regionCode: '019',
        countryCode: 76,
        countryCodeLetters: 'BR',
        area: 8511965,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/br.svg)',
    },
    {
        countryEn: 'China',
        countryRu: 'Китай',
        regionEn: 'Asia',
        regionRu: 'Азия',
        population: 1330044000,
        capitalEn: 'Beijing',
        capitalRu: 'Пекин',
        regionCode: '142',
        countryCode: 156,
        countryCodeLetters: 'CN',
        area: 9596960,
        flag: 'url(https://flagicons.lipis.dev/flags/4x3/cn.svg)',
    },
    {
        countryEn: 'United States of America',
        countryRu: 'Соединенные Штаты',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 310232863,
        capitalEn: 'Washington',
        capitalRu: 'Вашингтон',
        regionCode: '019',
        countryCode: 840,
        countryCodeLetters: 'US',
        area: 9629091,
    },
    {
        countryEn: 'Canada',
        countryRu: 'Канада',
        regionEn: 'Americas',
        regionRu: 'Америка',
        population: 33679000,
        capitalEn: 'Ottawa',
        capitalRu: 'Оттава',
        regionCode: '019',
        countryCode: 124,
        countryCodeLetters: 'CA',
        area: 9984670,
    },
    {
        countryEn: 'Russian Federation',
        countryRu: 'Россия',
        regionEn: 'Europe',
        regionRu: 'Европа',
        population: 140702000,
        capitalEn: 'Moscow',
        capitalRu: 'Москва',
        regionCode: '150',
        countryCode: 643,
        countryCodeLetters: 'RU',
        area: 17100000,
    },
    {
        countryEn: 'Cocos (Keeling) Islands',
        countryRu: 'Кокосовые (Килинг) острова',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 628,
        capitalEn: 'West Island',
        capitalRu: 'Западный остров',
        regionCode: '009',
        countryCode: 166,
        countryCodeLetters: 'CC',
        area: 14,
    },
    {
        countryEn: 'Nauru',
        countryRu: 'Науру',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 10065,
        capitalEn: 'Yaren District',
        capitalRu: 'Яренский район',
        regionCode: '009',
        countryCode: 520,
        countryCodeLetters: 'NR',
        area: 21,
    },
    {
        countryEn: 'Tuvalu',
        countryRu: 'Тувалу',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 10472,
        capitalEn: 'Funafuti',
        capitalRu: 'Фунафути',
        regionCode: '009',
        countryCode: 798,
        countryCodeLetters: 'TV',
        area: 26,
    },
    {
        countryEn: 'Pitcairn',
        countryRu: 'Острова Питкэрн',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 46,
        capitalEn: 'Adamstown',
        capitalRu: 'Адамстаун',
        regionCode: '009',
        countryCode: 612,
        countryCodeLetters: 'PN',
        area: 47,
    },
    {
        countryEn: 'Christmas Island',
        countryRu: 'Остров Рождества',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 1500,
        capitalEn: 'Flying Fish Cove',
        capitalRu: 'Бухта Летучей Рыбы',
        regionCode: '009',
        countryCode: 162,
        countryCodeLetters: 'CX',
        area: 135,
    },
    {
        countryEn: 'American Samoa',
        countryRu: 'Американское Самоа',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 57881,
        capitalEn: 'Pago Pago',
        capitalRu: 'Паго-Паго',
        regionCode: '009',
        countryCode: 16,
        countryCodeLetters: 'AS',
        area: 199,
    },
    {
        countryEn: 'Cook Islands',
        countryRu: 'Острова Кука',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 21388,
        capitalEn: 'Avarua',
        capitalRu: 'Аваруа',
        regionCode: '009',
        countryCode: 184,
        countryCodeLetters: 'CK',
        area: 240,
    },
    {
        countryEn: 'Niue',
        countryRu: 'Ниуэ',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 2166,
        capitalEn: 'Alofi',
        capitalRu: 'Алофи',
        regionCode: '009',
        countryCode: 570,
        countryCodeLetters: 'NU',
        area: 260,
    },
    {
        countryEn: 'Wallis and Futuna',
        countryRu: 'Уоллис и Футуна',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 16025,
        capitalEn: 'Mata-Utu',
        capitalRu: 'Мата-Уту',
        regionCode: '009',
        countryCode: 876,
        countryCodeLetters: 'WF',
        area: 274,
    },
    {
        countryEn: 'Heard Island and McDonald Islands',
        countryRu: 'Острова Херд и Макдональдс',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 0,
        capitalEn: '',
        capitalRu: '',
        regionCode: '009',
        countryCode: 334,
        countryCodeLetters: 'HM',
        area: 412,
    },
    {
        countryEn: 'Palau',
        countryRu: 'Палау',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 19907,
        capitalEn: 'Ngerulmud',
        capitalRu: 'Нгерулмуд',
        regionCode: '009',
        countryCode: 585,
        countryCodeLetters: 'PW',
        area: 458,
    },
    {
        countryEn: 'Northern Mariana Islands',
        countryRu: 'Северные Марианские острова',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 53883,
        capitalEn: 'Saipan',
        capitalRu: 'Сайпан',
        regionCode: '009',
        countryCode: 580,
        countryCodeLetters: 'MP',
        area: 477,
    },
    {
        countryEn: 'Guam',
        countryRu: 'Гуам',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 159358,
        capitalEn: 'Hagåtña',
        capitalRu: 'Хагатна',
        regionCode: '009',
        countryCode: 316,
        countryCodeLetters: 'GU',
        area: 549,
    },
    {
        countryEn: 'Micronesia (Federated States of)',
        countryRu: 'Микронезия',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 107708,
        capitalEn: 'Palikir',
        capitalRu: 'Паликир',
        regionCode: '009',
        countryCode: 583,
        countryCodeLetters: 'FM',
        area: 702,
    },
    {
        countryEn: 'Tonga',
        countryRu: 'Тонга',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 122580,
        capitalEn: "Nuku'alofa",
        capitalRu: 'Нукуалофа',
        regionCode: '009',
        countryCode: 776,
        countryCodeLetters: 'TO',
        area: 748,
    },
    {
        countryEn: 'Kiribati',
        countryRu: 'Кирибати',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 92533,
        capitalEn: 'Tarawa',
        capitalRu: 'Тарава',
        regionCode: '009',
        countryCode: 296,
        countryCodeLetters: 'KI',
        area: 811,
    },
    {
        countryEn: 'Samoa',
        countryRu: 'Самоа',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 192001,
        capitalEn: 'Apia',
        capitalRu: 'Апиа',
        regionCode: '009',
        countryCode: 882,
        countryCodeLetters: 'WS',
        area: 2944,
    },
    {
        countryEn: 'French Polynesia',
        countryRu: 'Французская Полинезия',
        regionEn: 'Oceania',
        regionRu: 'Океания',
        population: 270485,
        capitalEn: 'Papeete',
        capitalRu: 'Папеэте',
        regionCode: '009',
        countryCode: 258,
        countryCodeLetters: 'PF',
        area: 4167,
    },
];

export const africa = world.filter((el) => el.regionEn === 'Africa');
export const asia = world.filter((el) => el.regionEn === 'Asia');
export const oceania = world.filter((el) => el.regionEn === 'Oceania');
export const america = world.filter((el) => el.regionEn === 'America');
export const europe = world.filter((el) => el.regionEn === 'Europe');
