// google.charts.load("current", { packages: ["geochart"] });
// google.charts.setOnLoadCallback(drawRegionsMap);
// function drawRegionsMap() {
//   var data = google.visualization.arrayToDataTable([
//     ["Country", "#Participants"],
//     ["China", 4045],
//     ["United States of America", 2267],
//     ["India", 1281],
//     ["Germany", 444],
//     ["United Kingdom", 417],
//     ["South Korea", 334],
//     ["Canada", 310],
//     ["Netherlands", 278],
//     ["Iran", 231],
//     ["France", 217],
//     ["Japan", 194],
//     ["Spain", 156],
//     ["Brazil", 154],
//     ["Russia", 146],
//     ["Australia", 140],
//     ["Turkey", 135],
//     ["Pakistan", 134],
//     ["Taiwan", 132],
//     ["Singapore", 132],
//     ["Hong Kong", 98],
//     ["Poland", 97],
//     ["Italy", 96],
//     ["Israel", 94],
//     ["Switzerland", 91],
//     ["Egypt", 87],
//     ["Portugal", 61],
//     ["Colombia", 61],
//     ["Belgium", 53],
//     ["Vietnam", 49],
//     ["Greece", 43],
//     ["Norway", 41],
//     ["Malaysia", 41],
//     ["Austria", 40],
//     ["Sweden", 40],
//     ["Finland", 39],
//     ["Indonesia", 37],
//     ["Bangladesh", 37],
//     ["Hungary", 36],
//     ["Denmark", 33],
//     ["Belarus", 31],
//     ["Thailand", 31],
//     ["Afghanistan", 30],
//     ["Mexico", 30],
//     ["Ukraine", 30],
//     ["Sri Lanka", 25],
//     ["Ireland", 23],
//     ["Saudi Arabia", 22],
//     ["Philippines", 21],
//     ["Czechia", 21],
//     ["Tunisia", 20],
//     ["Morocco", 19],
//     ["Algeria", 19],
//     ["Romania", 18],
//     ["South Africa", 15],
//     ["New Zealand", 14],
//     ["Chile", 14],
//     ["Ethiopia", 13],
//     ["Peru", 11],
//     ["United Arab Emirates", 11],
//     ["Slovakia", 10],
//     ["Kazakhstan", 9],
//     ["Argentina", 9],
//     ["Slovenia", 9],
//     ["Qatar", 9],
//     ["Åland Islands", 8],
//     ["Albania", 8],
//     ["Nepal", 8],
//     ["Iraq", 8],
//     ["Serbia", 7],
//     ["American Samoa", 7],
//     ["Jordan", 7],
//     ["Bulgaria", 6],
//     ["Croatia", 6],
//     ["Bahrain", 6],
//     ["North Korea", 6],
//     ["Armenia", 6],
//     ["Estonia", 5],
//     ["Macao", 5],
//     ["Iceland", 4],
//     ["Andorra", 4],
//     ["Lithuania", 4],
//     ["Cyprus", 4],
//     ["Uganda", 3],
//     ["Cuba", 3],
//     ["Angola", 3],
//     ["Ecuador", 3],
//     ["Kenya", 3],
//     ["Libya", 3],
//     ["Zambia", 3],
//     ["Aruba", 3],
//     ["Bolivia", 3],
//     ["Latvia", 3],
//     ["Haiti", 3],
//     ["Bahamas", 3],
//     ["Macedonia", 3],
//     ["Azerbaijan", 2],
//     ["Oman", 2],
//     ["Syria", 2],
//     ["United States Minor Outlying Islands", 2],
//     ["Costa Rica", 2],
//     ["Sudan", 2],
//     ["Nigeria", 2],
//     ["Cocos (Keeling) Islands", 2],
//     ["Yemen", 2],
//     ["Antarctica", 2],
//     ["South Sudan", 2],
//     ["Dominica", 1],
//     ["Guam", 1],
//     ["Uruguay", 1],
//     ["Georgia", 1],
//     ["Zimbabwe", 1],
//     ["Congo", 1],
//     ["Gabon", 1],
//     ["Mozambique", 1],
//     ["Lebanon", 1],
//     ["Bosnia and Herzegovina", 1],
//     ["Barbados", 1],
//     ["Myanmar", 1],
//     ["Guinea", 1],
//     ["Saint Vincent and the Grenadines", 1],
//     ["Benin", 1],
//     ["Greenland", 1],
//     ["Venezuela", 1],
//     ["Togo", 1],
//     ["Saint Barthélemy", 1],
//     ["Lesotho", 1],
//     ["Trinidad and Tobago", 1],
//     ["Comoros", 1],
//     ["Guatemala", 1],
//     ["Burkina Faso", 1],
//     ["Belize", 1],
//     ["Mauritania", 1],
//     ["Virgin Islands (U.S.)", 1],
//     ["Namibia", 1],
//     ["Cambodia", 1],
//     ["Bouvet Island", 1],
//     ["Saint Helena, Ascension and Tristan da Cunha", 1],
//     ["Côte d'Ivoire", 1],
//     ["Cabo Verde", 1]
//   ]);
//   var options = {
//     colorAxis: {
//       colors: [
//       '#fbe723', '#f8e621', '#f4e61e', '#eae51a', '#d5e21a', '#aadc32', '#5cc863', '#21908d', '#440154'
//       ].reverse()
//     },
//     backgroundColor: "#c9eeff",
//     displayMode: "auto" // change this to "auto", "regions", "markers" or "text"
//   };
//   var chart = new google.visualization.GeoChart(
//     document.getElementById("chart")
//   );
//   chart.draw(data, options);
// }
